### ISSUE TITLE
compile error on centos 7

### ISSUE THREAD

**Issue by sharonsahadevan** [ClickHouse/clickhouse-odbc#116]
I am getting below error while compiling. please help.I followed the steps exactly.

[root@centos clickhouse-odbc]# mkdir -p build; cd build && cmake .. && make -j $(nproc || sysctl -n hw.ncpu || echo 4)
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: 
-- BUILD_SHARED=
-- Using ssl=1: /opt/softwares/clickhouse-odbc/contrib/ssl/include : ssl;crypto
-- Using ltdl: LTDL_LIBRARY-NOTFOUND
-- Could NOT find ODBC (missing: ODBC_INCLUDE_DIRECTORIES ODBC_LIBRARIES) 
-- Using odbc: ODBC_INCLUDE_DIRECTORIES-NOTFOUND : /usr/lib64/libodbc.so;/usr/lib64/libodbcinst.so;LTDL_LIBRARY-NOTFOUND
-- Using Poco: /opt/softwares/clickhouse-odbc/contrib/poco/NetSSL_OpenSSL/include;/opt/softwares/clickhouse-odbc/contrib/poco/Crypto/include : PocoFoundation,PocoUtil,PocoNet,PocoNetSSL,PocoCrypto,,,,,,; MongoDB=, DataODBC=, NetSSL=
-- Using nanoodbc= : 
-- Could NOT find ODBC (missing: ODBC_INCLUDE_DIRECTORIES ODBC_LIBRARIES) 
-- Using odbc: ODBC_INCLUDE_DIRECTORIES-NOTFOUND : /usr/lib64/libodbc.so;/usr/lib64/libodbcinst.so;LTDL_LIBRARY-NOTFOUND
-- Using odbc: ODBC_INCLUDE_DIRECTORIES-NOTFOUND : /usr/lib64/libodbc.so;/usr/lib64/libodbcinst.so;LTDL_LIBRARY-NOTFOUND
CMake Error at cmake/Modules/CheckODBCversion.cmake:15 (MESSAGE):
  unixodbc >= 2.3.0 required.

   RESULT=1 OUTPUT= ERROR=conftest.c:1:39: fatal error: sqlext.h: No such file or directory
   #include <sqlext.h>                   
                                         ^

  compilation terminated.

Call Stack (most recent call first):
  CMakeLists.txt:117 (include)

-- Configuring incomplete, errors occurred!
See also "/opt/softwares/clickhouse-odbc/build/CMakeFiles/CMakeOutput.log".
[root@centos build]# ls

**Comment by proller** [comment]
Di d you install unixodbc or libiodbc ? 
If you have not standard paths - pass them via cmake .. -DODBC_INCLUDE_DIRECTORIES=your/path/ -DODBC_LIBRARIES=/path/to.lib.so
