### ISSUE TITLE
Relative Date filters in Tableau fail

### ISSUE THREAD

**Issue by rookxyz** [ClickHouse/clickhouse-odbc#125]
### Issue
Cannot filter relative date from Tableau on a date type field.

### Steps To Repeat

1. From Tableau Connect to CH data source with a date column
2. Drag the date field to filters, select relative date, last X month, click Ok

### Error message in Tableau
```
HTTP status code: 404 Received error: Code: 50, e.displayText() = DB::Exception: Unknown data type family: TIMESTAMP, e.what() = DB::Exception
SELECT SUM(`a`.`val`) AS `sum_val_ok`
FROM `a`
WHERE ((CAST(`a`.`_date` AS TIMESTAMP) >= {ts '2018-05-01 00:00:00'}) AND (CAST(`a`.`_date` AS TIMESTAMP) < {ts '2018-11-01 00:00:00'}))
HAVING (COUNT(1) > 0)
```
### Software
- Tableau Desktop 2018.1.3 (64bit)
- Clickhouse db version: 18.12.17 revision 54407
- Clickhouse ODBC driver downloaded latest on 12th of July, 2018

**Comment by proller** [comment]
Should be fixed in server : https://github.com/yandex/ClickHouse/pull/3390
