### ISSUE TITLE
INSERT failed when using bind parameters.

### ISSUE THREAD

**Issue by ibrarahmad** [ClickHouse/clickhouse-odbc#136]
I am getting a not supported error message when trying to insert data using the bind parameter.
IM001:[unixODBC][Driver Manager]Driver does not support this function

**Comment by traceon** [comment]
Parameter statement support has beem added to the driver recently (you won't be getting this same error anymore). However there is a missing support of parametrized `INSERT`s at server side right now.

**Comment by filimonov** [comment]
> However there is a missing support of parametrized INSERTs at server side right now.

Fixed in the meanwhile: https://github.com/ClickHouse/ClickHouse/issues/7174
Should work with ClickHouse v19.16 and newer.
