### ISSUE TITLE
Remove ODBC {fn...} escape sequence

### ISSUE THREAD

**Issue by dfulachier** [ClickHouse/clickhouse-odbc#141]
ODBC driver version 2018-10-17 (1.00.00.61465)
Context: queries are generated from Tableau BI tool.

Some {fn...} ODBC secape sequences are let as it by ODBC driver, so ClickHouse server issues a SQL error.
Sample: SELECT {fn lower('AbcdE')}
The {fn...} should at least be removed by ODBC driver (the targetted function is well known and supported by ClickHouse server).

**Comment by proller** [comment]
Please show full list of unsupported functions needed for you.

lower and upper: https://github.com/yandex/clickhouse-odbc/pull/149

**Comment by dfulachier** [comment]
It is not so simple to get a full list. Tableau BI seems to systematically use ODBC escape sequence, so any function used by Tableau is concerned. Some examples (but not exhaustive...):
ABS, ACOS, ASIN, ASCII, ATAN, ATAN2, CEILING, CHAR, LOCATE, COS, COT, CHAR_LENGTH, SUBSTRING, LCASE, UCASE, etc.

**Comment by proller** [comment]
Most of them already supported -
https://github.com/yandex/clickhouse-odbc/blob/master/driver/escaping/function_declare.h
For other need to make support in clickhouse first

**Comment by apisarenco** [comment]
Unfortunately, using the latest release, I'm still getting these issues:
```{fn LEFT(....}```

```{fn CONVERT(large expression, SQL_BIGINT)```

I tried to debug, but with my absent experience with debugging DLLs, I got stuck.

**Comment by fbjoker** [comment]
I also met the same problem in use Tableau.Is that  week functions aren't working yet?
`HTTP status code: 400 Received error: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 789 (line 9, col 3): {fn WEEK(CAST(`X___SQL___`.`day` AS TIMESTAMP))} AS `wk_day_ok` FROM ( select tmp.*
 from 
 (select partner,day,channelname,all_uv,all_pv,all_pl,eight_uv. Unrecognized token`

**Comment by proller** [comment]
No, WEEK not supported yet.
First need to make same function in clickhouse server.

**Comment by alexey-milovidov** [comment]
@proller We have `toISOWeek` function in ClickHouse.

**Comment by proller** [comment]
done - https://github.com/yandex/clickhouse-odbc/commit/aac4204ae1c156691ef0df589819587f51495684

**Comment by filimonov** [comment]
Implemented in ClickHouse code.
