### ISSUE TITLE
Is ODBC driver managing ClickHouse Session ID?

### ISSUE THREAD

**Issue by dfulachier** [ClickHouse/clickhouse-odbc#143]
When I use ClickHouse through ODBC driver, from Tableau BI tool, no Session ID is transmitted to ClickHouse HTTP service. So Tableau cannot use temporary table (temporary table usage needs to use a session ID).
Is ClickHouse session ID managed by ODBC driver?

**Comment by nightweb** [comment]
I have simular problem. I propose to solve it differently: https://github.com/yandex/ClickHouse/issues/3842

**Comment by Enmk** [comment]
Closed by #398
