### ISSUE TITLE
odbc driver building on MacOS

### ISSUE THREAD

**Issue by cici20052016** [ClickHouse/clickhouse-odbc#159]
I followed ztlpn's code in this thread: https://github.com/yandex/clickhouse-odbc/issues/35
I got error when run this step: `cmake .. -DODBC_LIBRARIES=/usr/local/lib/libodbc.a`

-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: 
-- Using Poco: /Users/ylin/clickhouse-odbc/contrib/poco/Foundation/include/;/Users/ylin/clickhouse-odbc/contrib/poco/Util/include/;/Users/ylin/clickhouse-odbc/contrib/poco/Net/include/ : PocoFoundation,PocoUtil,PocoNet
-- Found ODBC: /Library/Frameworks/iODBC.framework/Headers  
CMake Error at cmake/Modules/CheckODBCversion.cmake:15 (MESSAGE):
  unixodbc >= 2.3.0 required.
Call Stack (most recent call first):
  CMakeLists.txt:63 (include)

-- Configuring incomplete, errors occurred!

**Comment by proller** [comment]
Try use /usr/local/lib/libiodbc.a (with i)

**Comment by proller** [comment]
Also try ```cmake .. ``` - now finding all libs should be successful automatically/

**Comment by cici20052016** [comment]
same error for `usr/local/lib/libiodbc.a (with i)` and `cmake .. `

-- CMAKE_BUILD_TYPE: 
-- Using Poco: /Users/ylin/clickhouse-odbc/contrib/poco/Foundation/include/;/Users/ylin/clickhouse-odbc/contrib/poco/Util/include/;/Users/ylin/clickhouse-odbc/contrib/poco/Net/include/ : PocoFoundation,PocoUtil,PocoNet
CMake Error at cmake/Modules/CheckODBCversion.cmake:15 (MESSAGE):
  unixodbc >= 2.3.0 required.
Call Stack (most recent call first):
  CMakeLists.txt:63 (include)


-- Configuring incomplete, errors occurred!

**Comment by traceon** [comment]
Please try with the current `master`.
