### ISSUE TITLE
Queries with JOINS and check for NULL are failing

### ISSUE THREAD

**Issue by Dima-HAN** [ClickHouse/clickhouse-odbc#166]
Hope anybody can help me to resolve this issue. Running Tableau connected to ClickHouse via ODBC driver. At first mostly any report request was failing. I have configured this tdc file https://github.com/yandex/clickhouse-odbc/blob/clickhouse-tbc/clickhouse.tdc and its actually started to work, however now some of the query requests with JOINS that contain check for NULL in ON are failing because of using **IS NULL** instead of **isNull(id)**

Appreciate any help!

`  JOIN users ON ((users.user_id = t0.user_id) OR ((users.user_id IS NULL) AND (t0.user_id IS NULL)))`

This is the correct way that works:

` JOIN users ON ((users.user_id = t0.user_id) OR ((isNull(users.user_id) = 1) AND (isNull(t0.user_id) = 1 IS NULL)))`

Not sure how to make tablau driver to send the right requerst

**Comment by yurifal** [comment]
You may want to use a Tableau calculation like this 
for every dimension used in joins, ditto LOD expressions:
 
`IFNULL( [your_string_dimension_used_in_join], '' )`

[Link to the thread on Tableau Forums](https://community.tableau.com/message/856536#856536)

Yours,
Yuri

**Comment by filimonov** [comment]
That can't be / and should be fixed on the driver side.
Please follow https://github.com/ClickHouse/ClickHouse/issues/3830
