### ISSUE TITLE
Ошибка Windows 10 / ODBC / Excel / Power BI

### ISSUE THREAD

**Issue by Papay** [ClickHouse/clickhouse-odbc#168]
Office 365 Excel 32-bit (16.0.11425.20200)
Настроил 32-bit драйвер Clickhouse - указал host/port/user
В Excel выбираю соединение источник данных ODBC и в конце вылетет диалог что неизвестная ошибка, ситуюция такая же и при подключении в Power BI.
Нужно ли в процессе подключения в Excel / Power BI указывать еще какие-либо параметры (строка подключения?) ?
Драйвер устанавливал последний доступный в github репозитории.
Работает ли вообще последний драйвер с этой версией Excel?

**Comment by traceon** [comment]
Issues mentioned here, with a good chance, are fixed by https://github.com/ClickHouse/clickhouse-odbc/pull/211 once it is merged.

**Comment by filimonov** [comment]
Fixed in 1.1.2.
See https://www.altinity.com/blog/2019/12/19/connecting-excel-to-clickhouse-using-the-windows-odbc-driver
