### ISSUE TITLE
MacOS pyodbc error

### ISSUE THREAD

**Issue by darthunix** [ClickHouse/clickhouse-odbc#172]
Hi!
I have successfully installed clickhouse-odbc with 

```
brew install https://raw.githubusercontent.com/proller/homebrew-core/chodbc/Formula/clickhouse-odbc.rb
```

Dylib file is on the propper place and seems to have all dependences
```
$ otool -L /usr/local/opt/clickhouse-odbc/lib/libclickhouseodbcw.dylib
/usr/local/opt/clickhouse-odbc/lib/libclickhouseodbcw.dylib:
	/usr/local/opt/clickhouse-odbc/lib/libclickhouseodbcw.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

But when I run a simple pyodbc test I get an error 
```
import pyodbc
driver_ch="/usr/local/opt/clickhouse-odbc/lib/libclickhouseodbcw.dylib"
cnxn = pyodbc.connect(driver=driver_ch, server='localhost', port='8123')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY000', 'The driver did not supply an error!')
```

[This](https://github.com/mkleehammer/pyodbc/blob/master/src/errors.cpp#L179) is a default PyODBC error with a [description](https://github.com/mkleehammer/pyodbc/blob/45395fe723b837e836643897ff3df57034c05b22/src/errors.cpp#L333)
```
This only happens using unixODBC.  (Haven't tried iODBC yet.)  Either the driver or the driver manager is buggy and has signaled a fault without recording error information.
```

So what am I doing wrong or is it a bug?

**Comment by filimonov** [comment]
It looks like pyodbc tries to use unixODBC driver manager against driver for iodbc driver manager.

https://github.com/mkleehammer/pyodbc/issues/444

So it looks you should either compile clickhouse-odbc agsinst unixODBC and use that unixodbc driver for Python connection, either patch pyodbc install to use iodbc
