### ISSUE TITLE
Error reporting when make（clickhouse-odbc-1.0.0.20190523）

### ISSUE THREAD

**Issue by ethanryl** [ClickHouse/clickhouse-odbc#178]
CMakeFiles/ load_ut.dir /load.cpp.o: in function 'main' :
/ software/clickhouse - odbc - 1.0.0.20190523 / driver/ut/load. CPP: 11: the 'Poco: : SharedLibrary: : SharedLibrary (STD: : __cxx11: : basic_string < char, STD: : char_traits < char >, STD: : allocator < char > > const &)' undefined reference
/ software/clickhouse - odbc - 1.0.0.20190523 / driver/ut/load. CPP: 14: "Poco: : SharedLibrary: : hasSymbol (STD: : __cxx11: : basic_string < char, STD: : char_traits < char >, STD: : allocator < char > > const &) 'undefined reference
/ software/clickhouse - odbc - 1.0.0.20190523 / driver/ut/load. CPP: 18: the 'Poco: : SharedLibrary: : getSymbol (STD: : __cxx11: : basic_string < char, STD: : char_traits < char >, STD: : allocator < char > > const &)' undefined reference
Error: ld returns 1
Make [2]: *** [driver/ut/load-ut] error 1
Make [1] : * * * / driver/ut/CMakeFiles/load - ut. Dir/all] 2
Make [1]: *** is waiting for an unfinished task...
[12] Built target clickhouseodbc-log
Linking CXX static library libgtest-lib.a
[15%] Built target gtest-lib
Make: *** [all] error 2

**Comment by proller** [comment]
Which os do you use?
Can you show full cmake console output ?

**Comment by ethanryl** [comment]
Red Hat Enterprise Linux Server release 7.5 (Maipo)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)


thanks for you.




------------------ 原始邮件 ------------------
发件人: "proller"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 下午5:46
收件人: "yandex/clickhouse-odbc"<clickhouse-odbc@noreply.github.com>;
抄送: "下一个明天"<810128618@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yandex/clickhouse-odbc] Error reporting when make（clickhouse-odbc-1.0.0.20190523） (#178)




Which os do you use?
 Can you show full cmake console output ?

**Comment by ethanryl** [comment]
[root@master build]# cmake ..
-- CMAKE_BUILD_TYPE: 
-- BUILD_SHARED=
CMake Warning at cmake/find_ssl.cmake:8 (message):
  submodule contrib/ssl is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:90 (include)


-- Using ssl=TRUE: /usr/include : /usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- lsb_release -cs: Maipo
-- Using ltdl: /usr/lib64/libltdl.so
-- Found ODBC: /usr/include  
-- Using odbc: /usr/include : /usr/lib64/libodbc.so;/usr/lib64/libodbcinst.so;/usr/lib64/libltdl.so  ODBC_IODBC=0 ODBC_UNIXODBC=1
CMake Warning at cmake/find_poco.cmake:5 (message):
  submodule contrib/poco is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)


-- Found Poco: optimized;/usr/local/lib/libPocoNet.a;optimized;/usr/local/lib/libPocoCrypto.a;optimized;/usr/local/lib/libPocoNetSSL.a;optimized;/usr/local/lib/libPocoUtil.a;optimized;/usr/local/lib/libPocoFoundation.a
-- Using Poco: /usr/local/include;/usr/local/include;/usr/local/include;/usr/local/include;/usr/local/include;/usr/local/include;/usr/include : /usr/local/lib/libPocoFoundation.a,/usr/local/lib/libPocoUtil.a,/usr/local/lib/libPocoNet.a,/usr/local/lib/libPocoNetSSL.a;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so,/usr/local/lib/libPocoCrypto.a,,,,,,; MongoDB=, DataODBC=, NetSSL=
-- Using nanoodbc= : 
-- Found ODBC: /usr/include  
-- Using odbc: /usr/include : /usr/lib64/libodbc.so;/usr/lib64/libodbcinst.so;/usr/lib64/libltdl.so;/usr/lib64/libodbcinst.so;/usr/lib64/libltdl.so  ODBC_IODBC=0 ODBC_UNIXODBC=1
-- Using odbc: /usr/include : /usr/lib64/libodbc.so;/usr/lib64/libodbcinst.so;/usr/lib64/libltdl.so;/usr/lib64/libodbcinst.so;/usr/lib64/libltdl.so
-- Building for: Linux-3.10.0-862.el7.x86_64 x86_64  ; CCACHE=CCACHE_FOUND-NOTFOUND 
-- clickhouse-odbc: UNICODE=0 SQL_WCHART_CONVERT=OFF ODBC_WCHAR= ODBC_CHAR16=
-- clickhouse-odbcw: UNICODE=1 SQL_WCHART_CONVERT=OFF ODBC_WCHAR= ODBC_CHAR16=
-- Testing with: TEST_DSN= TEST_DSN_W= ISQL=/usr/bin/isql IODBCTEST=IODBCTEST-NOTFOUND IODBCTESTW=IODBCTESTW-NOTFOUND
-- compiler C   = /usr/bin/cc  -O2 -g -DNDEBUG
-- compiler CXX = /usr/bin/c++  -O2 -g -fvisibility-inlines-hidden -O2 -g -DNDEBUG
-- LINKER_FLAGS =  
-- Configuring done
-- Generating done
-- Build files have been written to: /software/clickhouse-odbc-1.0.0.20190523/build


[root@master build]# make -j 4
[  5%] Built target gtest-lib
[ 10%] Built target clickhouse-odbc-log
[ 12%] Linking CXX executable load-ut
[ 20%] Built target clickhouse-odbc-escaping
/usr/local/lib/libPocoFoundation.a(SharedLibrary.cpp.o): In function `Poco::SharedLibrary::~SharedLibrary()':
(.text+0xf3): undefined reference to `operator delete(void*, unsigned long)'
/usr/local/lib/libPocoFoundation.a(Exception.cpp.o): In function `Poco::Exception::clone() const':
(.text+0x1887): undefined reference to `operator delete(void*, unsigned long)'
/usr/local/lib/libPocoFoundation.a(Exception.cpp.o): In function `Poco::LogicException::clone() const':
(.text+0x1b27): undefined reference to `operator delete(void*, unsigned long)'
/usr/local/lib/libPocoFoundation.a(Exception.cpp.o): In function `Poco::AssertionViolationException::clone() const':
(.text+0x1c77): undefined reference to `operator delete(void*, unsigned long)'
/usr/local/lib/libPocoFoundation.a(Exception.cpp.o): In function `Poco::NullPointerException::clone() const':
(.text+0x1dc7): undefined reference to `operator delete(void*, unsigned long)'
/usr/local/lib/libPocoFoundation.a(Exception.cpp.o):(.text+0x1f17): more undefined references to `operator delete(void*, unsigned long)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [driver/ut/load-ut] Error 1
make[1]: *** [driver/ut/CMakeFiles/load-ut.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 30%] Built target clickhouse-odbc-ut
[ 33%] Building CXX object driver/CMakeFiles/clickhouse-odbc.dir/attr.cpp.o
[ 35%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/config.cpp.o
[ 38%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/attr.cpp.o
In file included from /software/clickhouse-odbc-1.0.0.20190523/driver/config.h:4:0,
                 from /software/clickhouse-odbc-1.0.0.20190523/driver/config.cpp:1:
/software/clickhouse-odbc-1.0.0.20190523/driver/unicode_t.h:3:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
                   ^
compilation terminated.
[ 41%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/connection.cpp.o
make[2]: *** [driver/CMakeFiles/clickhouse-odbcw.dir/config.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object driver/CMakeFiles/clickhouse-odbc.dir/config.cpp.o
In file included from /software/clickhouse-odbc-1.0.0.20190523/driver/config.h:4:0,
                 from /software/clickhouse-odbc-1.0.0.20190523/driver/config.cpp:1:
/software/clickhouse-odbc-1.0.0.20190523/driver/unicode_t.h:3:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
                   ^
compilation terminated.
make[2]: *** [driver/CMakeFiles/clickhouse-odbc.dir/config.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /software/clickhouse-odbc-1.0.0.20190523/driver/utils.h:7:0,
                 from /software/clickhouse-odbc-1.0.0.20190523/driver/attr.cpp:7:
/software/clickhouse-odbc-1.0.0.20190523/driver/unicode_t.h:3:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
                   ^
compilation terminated.
In file included from /software/clickhouse-odbc-1.0.0.20190523/driver/utils.h:7:0,
                 from /software/clickhouse-odbc-1.0.0.20190523/driver/attr.cpp:7:
/software/clickhouse-odbc-1.0.0.20190523/driver/unicode_t.h:3:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
                   ^
compilation terminated.
In file included from /software/clickhouse-odbc-1.0.0.20190523/driver/config.h:4:0,
                 from /software/clickhouse-odbc-1.0.0.20190523/driver/connection.cpp:5:
/software/clickhouse-odbc-1.0.0.20190523/driver/unicode_t.h:3:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
                   ^
compilation terminated.
make[2]: *** [driver/CMakeFiles/clickhouse-odbcw.dir/connection.cpp.o] Error 1
make[2]: *** [driver/CMakeFiles/clickhouse-odbc.dir/attr.cpp.o] Error 1
make[2]: *** [driver/CMakeFiles/clickhouse-odbcw.dir/attr.cpp.o] Error 1
make[1]: *** [driver/CMakeFiles/clickhouse-odbc.dir/all] Error 2
make[1]: *** [driver/CMakeFiles/clickhouse-odbcw.dir/all] Error 2
make: *** [all] Error 2

**Comment by filimonov** [comment]
Are you building from tar.gz?

Please try to use `git clone --recursive` as in Readme.

**Comment by proller** [comment]
`fatal error: codecvt: No such file or directory` -  looks like you have too old gcc (with old stdlib).
Please try use gcc5+
