### ISSUE TITLE
Windows 10 ODBC 64bit msi file does not create data source

### ISSUE THREAD

**Issue by wirkix** [ClickHouse/clickhouse-odbc#189]
Hi all!

I recently downloaded and installed the clickhouse_odbc_x64.msi file release 1.0.0.20190611 from https://github.com/yandex/clickhouse-odbc/releases, but when I opened ODBC Data Sources to create a new data source, both options (ANSI and Unnicode) opened the window to type the parameters and failed to actually create the data source.

Here are some screeen captures:

![image](https://user-images.githubusercontent.com/47483311/62296386-f7cdae00-b43c-11e9-9cfa-a493f23bd549.png)
Here you can see that Clickhouse ODBC client for Windows was successfully installed.

![image](https://user-images.githubusercontent.com/47483311/62296437-12a02280-b43d-11e9-9949-cc1c5a9db84a.png)
After clicking OK in this window, the data source does not appear in the list below.

![image](https://user-images.githubusercontent.com/47483311/62296467-2186d500-b43d-11e9-924b-76f3ceec88d7.png)

I have tried several times. I have uninstalled and re-installed the ODBC client, and tried both with ANSI and Unicode unsuccessfully. So, I'm asking myself now if I'm doing something wrong or if this is a known issue with the ODBC client for Windows? Is there any workaround to solve this problem? I need to create a new data source for Clickhouse so I can see my data from Power BI.

Thanks for any help you can give!
Greetings!

**Comment by proller** [comment]
Install both clickhouse_odbc_x64.msi and clickhouse_odbc_x32.msi

**Comment by traceon** [comment]
Please give this a try: https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.1.20191108
