### ISSUE TITLE
Ошибка компиляции CentOs

### ISSUE THREAD

**Issue by ELDIABLO4400** [ClickHouse/clickhouse-odbc#190]
CentOS release 6.9 (Final)
PostgreSQL 11.4 on x86_64-pc-linux-gnu
ClickHouse client version 19.9.5.36.
gcc (GCC) 9.1.0
cmake version 3.15.1

[ 98%] Built target clickhouse-odbc-escaping
Scanning dependencies of target clickhouse-odbcw
[ 98%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/attr.cpp.o
[ 98%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/config.cpp.o
[ 98%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/connection.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/diagnostics.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/environment.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/handles.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/info.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/odbc.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/read_helpers.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/result_set.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/statement.cpp.o
[ 99%] Building CXX object driver/CMakeFiles/clickhouse-odbcw.dir/type_parser.cpp.o
[ 99%] Linking CXX shared library libclickhouseodbcw.so
/usr/bin/ld: /usr/local/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../libltdl.a(libltdl_libltdl_la-ltdl.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../libltdl.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [driver/libclickhouseodbcw.so] Error 1
make[1]: *** [driver/CMakeFiles/clickhouse-odbcw.dir/all] Error 2
make: *** [all] Error 2

**Comment by proller** [comment]
Try specify full path to ltdl.so:
cmake  -DLTDL_LIBRARY=/usr/local/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../libltdl.so
