### ISSUE TITLE
Error building on debian or ubuntu

### ISSUE THREAD

**Issue by sepal** [ClickHouse/clickhouse-odbc#193]
Hey, 
I'm trying to compile the driver for linux and I'm the get the following error:

```
[100%] Linking CXX shared library libclickhouseodbc.so                                 
usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libltdl.a(libltdl_libltdl_la-lt__alloc.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
```

I tried ubuntu and debian docker images as well as compiling manually in a vagrant/vm box using "debian/buster64"

libltdl-dev is installed automatically on both systems, and I followed the instructions in the readme.

I guess I would need to add the `-fPIC` somewhere, but I'm not sure where.

**Comment by proller** [comment]
Please update and try again
https://github.com/yandex/clickhouse-odbc/commit/d81b9d7952c0e66deace3fabf55a67ebfbbb604a

**Comment by MaoShultz** [comment]
update not solve the problem

**Comment by sepal** [comment]
I was able to compile it in the vagrant vm. On docker the fix won't work since `lsb_release` is not avialable, but you could check `/etc/issue`.

**Comment by traceon** [comment]
Please retry with current `master`.
