### ISSUE TITLE
clickhouse_odbc_x64.msi can't install on windows server 2012 R2.

### ISSUE THREAD

**Issue by linux2014linux** [ClickHouse/clickhouse-odbc#199]
I try install clickhouse_odbc_x64.msi to windows server 2012 R2. But status is still "Validating Install". 
![2019-10-14_105318](https://user-images.githubusercontent.com/7777721/66727339-11de3080-ee71-11e9-8c82-e7a52c009505.png)
Then I install x64.msi by command "C:\Windows\SysWOW64>msiexec.exe  /i D:\Download\clickhouse_odbc_x64.msi /L*V D:\Download\install.log". Some error info is recorded to log. Error information is "MSI (s) (80:DC) [10:44:36:278]: RESTART MANAGER: Failed to retrieve the list of applications that hold files in use; Windows Installer will use the built-in FilesInUse functionality. Error: 6".

**Comment by filimonov** [comment]
Try to rerun installation with admin privileges.
If problem persists - please attach full installation log. 

Similar issue (other software): https://www.lansweeper.com/forum/yaf_postsm55477findlastpost_MSI-Deployment-Question.aspx#post55487

**Comment by traceon** [comment]
Also, it is worth trying the latest release MSIs from https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.0.20191028

**Comment by linux2014linux** [comment]
@traceon Thank you very much! It works!
