### ISSUE TITLE
SSIS ODBC Destination error no schema ( no collumn info )

### ISSUE THREAD

**Issue by Ramaseb** [ClickHouse/clickhouse-odbc#202]
I have installed ODBC driver ver 1.00.00.5523 ( ANSI / UNICODE ) on Windows 10 ver 19.03.
I have Visual Studio Community 16.3.6 with SSIS extentions installed.
On a dataflow Task with ODBC Destination with a DSN ( unicode ) to ClickHouse server to a database with a table on LOG engine , no collumns are present in the designer !
if collumns created manual on the ODBC Destination the execution of the datalow fails with error , no  collumn info on ODBC Destination.

**Comment by filimonov** [comment]
Probably duplicate: https://github.com/ClickHouse/clickhouse-odbc/issues/176  (but 176 is in Russian, so let's keep both)

**Comment by Ramaseb** [comment]
Hi ,
any news on this ?

**Comment by traceon** [comment]
Issues mentioned here, with a good chance, are fixed by https://github.com/ClickHouse/clickhouse-odbc/pull/211 once it is merged.

**Comment by traceon** [comment]
Please try https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.2.20191216

**Comment by Ramaseb** [comment]
Hi , thank you for your effords.
It seems that now I can't get a data preview , and no collumns info , as it was before.
I receive from #176  updates and it states that the problems exists because of SSIS bug !!. I'am using SSIS with 3-4 different database vendors and SSIS has no problem !!!. If you can fix the behavior of the ODBC drivers it wil be a major plus for this awesome product.

**Comment by traceon** [comment]
> It seems that now I can't get a data preview , and no collumns info , as it was before.

Could you tell us which version of driver you were able to get column data exactly?
Also, as stated in #176, the preview will work for tables from the database that matches the database from DSN. Were you able to preview data from table of *any* other database with that old version? Your accurate answers will help us to roll out fixes much sooner. Thanks!

**Comment by filimonov** [comment]
Fixed in https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.3.20200115
