### ISSUE TITLE
При импорте данных в Табло на macOS добавляются пустые строки

### ISSUE THREAD

**Issue by pavelkuligin** [ClickHouse/clickhouse-odbc#206]
OS: 10.15.1
Tableau: 2019.3.1

1. Установил драйвер ODBC через версию для девелоперов (простая установка не работает, не может найти ветку: warning: Could not find remote branch v1.0.0.20191028 to clone) с unixodbc.
2. Подключился к Кликхаусу
3. При загрузке таблиц вставляются пустые строки, скриншот прикреплен
![image](https://user-images.githubusercontent.com/27766810/68078294-b1744c00-fda9-11e9-815e-6d3806389548.png)

У коллеги при той же конфигурации все ок, единственное он устанавливал через простую установку ранее и проблем не было.

**Comment by KuliginStepan** [comment]
Удалось найти причину: проблема выше происходит с драйвером последней версии. На предыдущей версии 20190611 все работает правильно

**Comment by filimonov** [comment]
Спасибо за рапорт. Будем пытаться воспроизвести / искать причину.

Два вопроса
1) как настроен DSN кликхауса
2) есть ли возможность включить логирование в драйвере?
Для DSN нужно указать `trace=1` и `tracefile=/tmp/clickhouse-odbc.log`. Потом запустить импорт, убедиться что дубликаты на месте, и отправить лог сюда

**Comment by traceon** [comment]
Драйвер построен с iODBC, верно?

Tableau под macOS предсказуемо использует системную имплементацию ODBC Driver Manager (т.е. iODBC), а значит и драйвер должен быть построен с iODBC.

**Comment by filimonov** [comment]
Починили "простую" установку, попробуйте ещё раз.

Возможно проблема связано с тем что Вы собрали драйвер с unixODBC, а используете его с iodbc в качестве менеджера драйверов.

**Comment by KuliginStepan** [comment]
Так настроен DSN в файле odbc.ini
```
[ClickHouse]
Driver      = /Users/stepan/clickhouse-odbc/build/driver/libclickhouseodbcw.dylib
Description = ClickHouse driver
server      = clickhouse
database    = default
uid         = default
port        = 8123
trace       = 1
tracefile   = /tmp/clickhouse-odbc.log
```
Логи драйвера после подключения к табло и импорта таблицы с пустыми строками
[clickhouse-odbc.log](https://github.com/ClickHouse/clickhouse-odbc/files/3803424/clickhouse-odbc.log)

Проблема для нас оказалась характерна не только для macOS, на windows вчера была идентичная проблема, которая решилась даунгрейдом версии драйвера

**Comment by KuliginStepan** [comment]
@filimonov мы собирали не через unixodbc, это была ошибка в первом сообщении. Мы делали unlink unixodbc

**Comment by KuliginStepan** [comment]
После установки последней версии через brew проблема осталась, логи драйвера
[clickhouse-odbc.log](https://github.com/ClickHouse/clickhouse-odbc/files/3803518/clickhouse-odbc.log)

**Comment by filimonov** [comment]
Fixed in https://github.com/ClickHouse/clickhouse-odbc/pull/208

**Comment by traceon** [comment]
Please give this a try: https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.1.20191108
