### ISSUE TITLE
Create & test Tableau Datasource Customization (TDC) file

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/clickhouse-odbc#210]
See documentation: https://onlinehelp.tableau.com/current/pro/desktop/en-us/odbc_capabilities.htm

Here is untested, community provided tbc file: [clickhouse.tdc.zip](https://github.com/ClickHouse/clickhouse-odbc/files/3816232/clickhouse.tdc.zip)

**Comment by yurifal** [comment]
For the Tableau to recognise the TDC and to apply the customisations, 
the <vendor name> tag should be re-written as 

`<vendor name='ClickHouse' />
`

**Comment by filimonov** [comment]
Some related links & issues:
https://github.com/ClickHouse/ClickHouse/issues/3830 
https://github.com/ClickHouse/clickhouse-odbc/issues/166

https://community.tableau.com/ideas/6454 + https://www.google.com/search?q=clickhouse+site%3Acommunity.tableau.com&ie=utf-8&oe=utf-8

**Comment by traceon** [comment]
Please try TDC from https://github.com/ClickHouse/clickhouse-odbc/pull/226 and share your thoughts. Thanks.

**Comment by filimonov** [comment]
official info have also some more info: https://help.tableau.com/current/pro/desktop/en-us/odbc_tableau.htm
