### ISSUE TITLE
Проект не собирается в VS 2019 community edition

### ISSUE THREAD

**Issue by jdeshin** [ClickHouse/clickhouse-odbc#213]
При попытке собрать проект в VS 2019 по информации из readme возникают ошибки вида:
C:\clickhouse-odbc\vs\driver64w\driver64w.vcxproj]
         c1xx : fatal error C1083: Cannot open source file: '..\..\driver\win\setup.cpp': No such file or directory [C:
       \clickhouse-odbc\vs\driver64w\driver64w.vcxproj]
При просмотре проектов в VS пути к файлам не соответствуют фактическому расположению файлов.
[git-clone.txt](https://github.com/ClickHouse/clickhouse-odbc/files/3876530/git-clone.txt)
[build.txt](https://github.com/ClickHouse/clickhouse-odbc/files/3876532/build.txt)

**Comment by traceon** [comment]
The README will be updated soon. Meanwhile, this are the steps for building in Windows using Visual Studio:
1. Install Visual Studio 2017+, with C++ x64 (or x86) targeting build tools, Windows SDK (using same VS installer), git (version shipped with VS can be used), cmake (version shipped with VS can be used), WiX Toolset (if you are going to make MSI packages, https://wixtoolset.org/releases/)
2. `git clone --recursive https://github.com/ClickHouse/clickhouse-odbc.git`
3. Create `<cloned-clickhouse-odbc-dir>/build` directory
4. Using `x64 Native Tools Command Prompt for VS 2019`-enabled console:
```
cd /D <cloned-clickhouse-odbc-dir>/build
cmake -A x64 -DCMAKE_BUILD_TYPE=Debug -DENABLE_NETSSL_WIN=1 -DTEST_DSN=ClickHouse_DSN_Debug -DTEST_DSN_W=ClickHouse_W_DSN_Debug ..
```
5. if step 4 succeeds without errors, run `cmake --open .` in the same command prompt and build the project in the opened Visual Studio GUI

**Comment by jdeshin** [comment]
Dear Denis.
Thank you a lot for your quick fix. I will try a new way, that you suggested as soon as possible.
Best regards,
Yury

________________________________
От: Denis Glazachev <notifications@github.com>
Отправлено: 22 ноября 2019 г. 0:52
Кому: ClickHouse/clickhouse-odbc <clickhouse-odbc@noreply.github.com>
Копия: jdeshin <j.deshin@hotmail.com>; Author <author@noreply.github.com>
Тема: Re: [ClickHouse/clickhouse-odbc] Проект не собирается в VS 2019 community edition (#213)


The README will be updated soon. Meanwhile, this are the steps for building in Windows using Visual Studio:

  1.  Install Visual Studio 2017+, with C++ x64 (or x86) targeting build tools, Windows SDK (using same VS installer), git (version shipped with VS can be used), cmake (version shipped with VS can be used), WiX Toolset (if you are going to make MSI packages, https://wixtoolset.org/releases/)
  2.  git clone --recursive https://github.com/ClickHouse/clickhouse-odbc.git
  3.  Create <cloned-clickhouse-odbc-dir>/build directory
  4.  Using x64 Native Tools Command Prompt for VS 2019-enabled console:

cd /D <cloned-clickhouse-odbc-dir>/build
cmake -A x64 -DCMAKE_BUILD_TYPE=Debug -DENABLE_NETSSL_WIN=1 -DTEST_DSN=ClickHouse_DSN_Debug -DTEST_DSN_W=ClickHouse_W_DSN_Debug ..


  1.  if step 4 succeeds without errors, run cmake --open . in the same command prompt and build the project in the opened Visual Studio GUI

**Comment by jdeshin** [comment]
[cid:3c6ffcda-bb16-4245-af20-d773988021ae]
Hello Denis.
I have tried your new method, but not successfull. Please see screenshot above.
The part of the log of your steps is below:
IN=1 -DTEST_DSN=ClickHouse_DSN_Debug -DTEST_DSN_W=ClickHouse_W_DSN_Debug ..
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27034.0
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: Debug
-- BUILD_SHARED:
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the sys
tem variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_D
IR)
-- Using ssl=1: C:/clickhouse-odbc/contrib/ssl/include : ssl;crypto
-- Using ltdl: LTDL_LIBRARY-NOTFOUND
-- Found ODBC: C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um
-- Using odbc: C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um :
C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/um/x86/odbc32.lib  ODBC_
IODBC= ODBC_UNIXODBC=
-- Using Poco: C:/clickhouse-odbc/contrib/poco/Foundation/include/;C:/clickhouse
-odbc/contrib/poco/Util/include/;C:/clickhouse-odbc/contrib/poco/Net/include/;C:
/clickhouse-odbc/contrib/poco/XML/include/;C:/clickhouse-odbc/contrib/poco/JSON/
include/;C:/clickhouse-odbc/contrib/poco/NetSSL_Win/include : Foundation,Util,Ne
t,NetSSLWin,,XML,JSON,,,,,; MongoDB=, DataODBC=, NetSSL=
-- Using nanoodbc= :
-- Using odbc: C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um :
C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/um/x86/odbc32.lib  ODBC_
IODBC= ODBC_UNIXODBC=
-- Windows native ODBC Support Enabled
-- Using odbc: C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um :
odbc32;odbccp32;legacy_stdio_definitions
-- Building for: Windows-6.3.9600 AMD64  ; CCACHE=CCACHE_FOUND-NOTFOUND
CMake Warning (dev) at contrib/ssl/CMakeLists.txt:11 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
    PROJECT_VERSION_TWEAK
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using [MSVC] compiler
-- Looking for asprintf
-- Looking for asprintf - not found
-- Looking for inet_pton
-- Looking for inet_pton - not found
-- Looking for strcasecmp
-- Looking for strcasecmp - not found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strndup
-- Looking for strndup - not found
-- Looking for strsep
-- Looking for strsep - not found
-- Looking for timegm
-- Looking for timegm - not found
-- Looking for arc4random_buf
-- Looking for arc4random_buf - not found
-- Looking for arc4random_uniform
-- Looking for arc4random_uniform - not found
-- Looking for explicit_bzero
-- Looking for explicit_bzero - not found
-- Looking for getpagesize
-- Looking for getpagesize - not found
-- Looking for timingsafe_bcmp
-- Looking for timingsafe_bcmp - not found
-- Looking for timingsafe_memcmp
-- Looking for timingsafe_memcmp - not found
-- Looking for memmem
-- Looking for memmem - not found
-- Looking for include file err.h
-- Looking for include file err.h - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of time_t
-- Check size of time_t - done
-- Poco package version: 1.9.4
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Checking for C++14 compiler
-- Checking for C++14 compiler - available
-- Found message compiler: C:/Program Files (x86)/Windows Kits/8.1/bin/x86/mc.ex
e
-- Building static libraries
-- Building without tests & samples
-- Using internal sqlite, zlib, pcre, expat, ...
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the sys
tem variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found version "
1.0.0")
-- CMake 3.12.18081601-MSVC_2 successfully configured Poco using Visual Studio 1
5 2017 generator
-- Installation target path: C:/Program Files (x86)/clickhouse-odbc
-- C_FLAGS:  =/DWIN32 /D_WINDOWS /W3
-- CMAKE_C_FLAGS_DEBUG:=/MTd /Zi /Ob0 /Od /RTC1
-- CMAKE_C_FLAGS_RELEASE:=/MT /O2 /Ob2 /DNDEBUG
-- CMAKE_C_FLAGS_MINSIZEREL:=/MT /O1 /Ob1 /DNDEBUG
-- CMAKE_C_FLAGS_RELWITHDEBINFO:=/MT /Zi /O2 /Ob1 /DNDEBUG
--
--
-- CXX_FLAGS:=/DWIN32 /D_WINDOWS /W3 /GR /EHsc /Zc:__cplusplus
-- CMAKE_CXX_FLAGS_DEBUG:=/MTd /Zi /Ob0 /Od /RTC1
-- CMAKE_CXX_FLAGS_RELEASE:=/MT /O2 /Ob2 /DNDEBUG
-- CMAKE_CXX_FLAGS_MINSIZEREL:=/MT /O1 /Ob1 /DNDEBUG
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO:=/MT /Zi /O2 /Ob1 /DNDEBUG
-- Building: XML
-- Building: JSON
-- Building: Util
-- Building: Net
-- Building: NetSSL_Win
-- clickhouse-odbc: ANSI
-- clickhouse-odbcw: Unicode
-- Testing with:
        TEST_DSN=ClickHouse_DSN_Debug
        TEST_DSN_W=ClickHouse_W_DSN_Debug
        PERL=PERL-NOTFOUND
        PERL_USES_UNIXODBC=0
        PERL_USES_IODBC=0
        PYTHON=PYTHON-NOTFOUND
        PYTHON_USES_UNIXODBC=0
        PYTHON_USES_IODBC=0
        ISQL=ISQL-NOTFOUND
        IUSQL=IUSQL-NOTFOUND
        IODBCTEST=IODBCTEST-NOTFOUND
        IODBCTESTW=IODBCTESTW-NOTFOUND
        SQLCMD=C:/Program Files/Microsoft SQL Server/110/Tools/Binn/SQLCMD.EXE
-- compiler C   = C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/
VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MTd /Zi
 /Ob0 /Od /RTC1
-- compiler CXX = C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/
VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /GR /EHs
c /Zc:__cplusplus /MTd /Zi /Ob0 /Od /RTC1
-- LINKER_FLAGS = /machine:x64 /debug /INCREMENTAL
-- Configuring done
-- Generating done
-- Build files have been written to: C:/clickhouse-odbc/build

As I undersand, you have successfully compiled a project.
Therefore, can you please give me an archive, that I can use?



________________________________
От: Denis Glazachev <notifications@github.com>
Отправлено: 22 ноября 2019 г. 0:52
Кому: ClickHouse/clickhouse-odbc <clickhouse-odbc@noreply.github.com>
Копия: jdeshin <j.deshin@hotmail.com>; Author <author@noreply.github.com>
Тема: Re: [ClickHouse/clickhouse-odbc] Проект не собирается в VS 2019 community edition (#213)


The README will be updated soon. Meanwhile, this are the steps for building in Windows using Visual Studio:

  1.  Install Visual Studio 2017+, with C++ x64 (or x86) targeting build tools, Windows SDK (using same VS installer), git (version shipped with VS can be used), cmake (version shipped with VS can be used), WiX Toolset (if you are going to make MSI packages, https://wixtoolset.org/releases/)
  2.  git clone --recursive https://github.com/ClickHouse/clickhouse-odbc.git
  3.  Create <cloned-clickhouse-odbc-dir>/build directory
  4.  Using x64 Native Tools Command Prompt for VS 2019-enabled console:

cd /D <cloned-clickhouse-odbc-dir>/build
cmake -A x64 -DCMAKE_BUILD_TYPE=Debug -DENABLE_NETSSL_WIN=1 -DTEST_DSN=ClickHouse_DSN_Debug -DTEST_DSN_W=ClickHouse_W_DSN_Debug ..


  1.  if step 4 succeeds without errors, run cmake --open . in the same command prompt and build the project in the opened Visual Studio GUI

**Comment by traceon** [comment]
Hi Yury,

Your log ends with:
```
....
-- Configuring done
-- Generating done
-- Build files have been written to: C:/clickhouse-odbc/build
```

...which is a exactly how it should end, to allow you to proceed to the next step of actually compiling sources using the generated Visual Studio project. After this, you are at the step # 5. Just issue `cmake --open .` command in the same prompt (or double-click `C:/clickhouse-odbc/build/clickhouse-odbc.sln` file) and you'll see Visual Studio window, from where you can compile the sources and build the MSI's by "building" the `package` project.

**Comment by jdeshin** [comment]
Hi Denis, after that I completed step 4, of course  I have tried perform step 5, but I received many errors. This screenshot does not appeared from my email. I think it's because something is missconfigured. 
![step5](https://user-images.githubusercontent.com/33670268/69451364-3b438380-0d70-11ea-9aac-a03a49a96d42.png)

**Comment by traceon** [comment]
Looks like there is a confusion between the target and detected Windows SDK bitness:

**Comment by jdeshin** [comment]
Dear Denis,
I successfully built the project with VS 2019 (not with VS 2017) by following steps 1-5 of your explanation. When I opened the solution in VS, I found that the clickhouse-odbcw-load-ut project is still VS 2017, and I manually changed it to VS 2019. Thanks a lot for your help! And I have a few more questions for you:
Why "install" project makes files in Program Files x86 folder?
How can I create msi package?

**Comment by traceon** [comment]
>  clickhouse-odbcw-load-ut project is still VS 2017

This is an indication of leftovers of previous configuration attempts using cmake and a different (in this case vs 2017 toolset). Always manual remove all files from your `C:/clickhouse-odbc/build` when you reconfigure.

>  Why "install" project makes files in Program Files x86 folder?

That will be fixed eventually, however you should not use `install` target directly. Instead, use `package` target and then install the generated `.msi` file (in `C:/clickhouse-odbc/build` dir). For `package` target to succeed, you need to have WiX Toolset installed, as recommended in step # 1.

**Comment by jdeshin** [comment]
Great, it works!
Thank you a lot!
Could you please indicate required version of VS is 2019 in your new description

**Comment by traceon** [comment]
Visual Studio 2017 should work too.

**Comment by traceon** [comment]
This can be closed.
