### ISSUE TITLE
Unicode driver version poor performance

### ISSUE THREAD

**Issue by zaaml** [ClickHouse/clickhouse-odbc#220]
Selecting 100k rows from .Net Core application on Windows 10 with ANSI driver takes around 1.5s, while with Unicode version it is about 22s. Profiling shows the reason is within [~/driver/utils/unicode_conv.h](https://github.com/ClickHouse/clickhouse-odbc/blob/master/driver/utils/unicode_conv.h) `fromUTF8` conversion routine. Every single string conversion invokes creation of `std::wstring_convert` instance. Moving out converter to `static thread_local` variable resolves issue, but I'm not sure this is an appropriate solution. What are your thoughts?

**Comment by traceon** [comment]
Maybe not a static (per-thread) instance, but, yes, reusing the same converter on a per-statement basis should work fine. Thanks for the find, we'll address this during our upcoming driver performance optimization efforts.

**Comment by traceon** [comment]
> Moving out converter to static thread_local variable resolves issue

@zaaml do you have the exact numbers after you applied this change?

**Comment by zaaml** [comment]
@traceon, I don't remember the exact numbers, but after my change there was almost no difference between Unicode and ANSI driver in execution time.

**Comment by traceon** [comment]
@zaaml I am asking this, because what I observe is that the most of the time is spent in the actual conversion call, not in `std::wstring_convert` construction. I made those objects static in the functions, and still have that terrible performance.

I am changing that whole Unicode conversion code though, just wanted to point out that I don't think this is as easy as avoiding `std::wstring_convert` recreation.

If you are absolutely sure that construction of `std::wstring_convert` is the cause of the slowdown, I would really appreciate if you could share your changes with the instructions on how to test and compare.

**Comment by zaaml** [comment]
Hi @traceon,

I created a sample .Net Core Console Application project ([ClickhouseOdbcPerfTest.zip](https://github.com/ClickHouse/clickhouse-odbc/files/4338257/ClickhouseOdbcPerfTest.zip)), which creates PerfTest table and seeds it with 100k rows data. All tests are performed on x64 Windows 10 (1809). Steps to reproduce:
1. install the latest ODBC driver.
2. create 2 dsn for both driver versions with the following names: CHAnsi and CHUnicode
3. open provided solution and run.

Clean install 64 bit ODBC driver:

Time for dsn 'CHAnsi': 936,4401ms
Time for dsn 'CHUnicode': 6174,3963ms

Clean source after git clone, build in Release configuration:

Time for dsn 'CHAnsi': 951,6071ms
Time for dsn 'CHUnicode': 6181,1695ms

After fix ([patch.zip](https://github.com/ClickHouse/clickhouse-odbc/files/4338270/patch.zip)) build in Release configuration:

Time for dsn 'CHAnsi': 943,7115ms
Time for dsn 'CHUnicode': 858,1065ms

Profiling project shows the most expensive call is in line 
`std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> convert;`

![profile](https://user-images.githubusercontent.com/36498644/76760322-7c87f500-679e-11ea-8125-56cb935ae3b7.png)

**Comment by traceon** [comment]
@zaaml Thank you for your example!

I was able to observe what you described, and it looks like this is the case where MSVC implementation differs from Linux/macOS (libstdc++/libc++) implementations of that `std::wstring_convert` and underlying facets.

I was testing and measuring mainly under Linux and macOS, so what I see is that with or without `std::wstring_convert` caching, the heaviest stack is always in `std::wstring_convert<>::from_bytes()` there, while this is not the case under Windows.

With or without your changes, the heaviest stack in macOS (and Linux) looks like this:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/10261534/76816298-49cf1280-6819-11ea-8c83-d5d4750fcb43.png">

I was testing with this stateless C++ case:
```diff
diff --git a/driver/test/performance_it.cpp b/driver/test/performance_it.cpp
index 315646a..0388d14 100755
--- a/driver/test/performance_it.cpp
+++ b/driver/test/performance_it.cpp
@@ -55,6 +55,59 @@ private:
     SQLUINTEGER driver_log = SQL_OPT_TRACE_ON;
 };

+TEST_F(PerformanceTest, UnicodeConverter) {
+    constexpr std::size_t total_rows_expected = 20'000'000;
+    const std::string query_orig = "SELECT CAST('some not very long text', 'String') AS col FROM numbers(" + std::to_string(total_rows_expected) + ")";
+
+    std::cout << "Executing query:\n\t" << query_orig << std::endl;
+
+    const auto query = fromUTF8<SQLTCHAR>(query_orig);
+    auto * query_wptr = const_cast<SQLTCHAR * >(query.c_str());
+
+    ODBC_CALL_ON_STMT_THROW(hstmt, SQLPrepare(hstmt, query_wptr, SQL_NTS));
+    ODBC_CALL_ON_STMT_THROW(hstmt, SQLExecute(hstmt));
+
+    SQLTCHAR col[10240] = {};
+    SQLLEN col_ind = 0;
+
+    std::size_t total_rows = 0;
+
+    START_MEASURING_TIME();
+
+    while (true) {
+        const SQLRETURN rc = SQLFetch(hstmt);
+
+        if (rc == SQL_NO_DATA)
+            break;
+
+        if (rc == SQL_ERROR)
+            throw std::runtime_error(extract_diagnostics(hstmt, SQL_HANDLE_STMT));
+
+        if (rc == SQL_SUCCESS_WITH_INFO)
+            std::cout << extract_diagnostics(hstmt, SQL_HANDLE_STMT) << std::endl;
+
+        if (!SQL_SUCCEEDED(rc))
+            throw std::runtime_error("SQLFetch return code: " + std::to_string(rc));
+
+        ODBC_CALL_ON_STMT_THROW(hstmt,
+            SQLGetData(
+                hstmt,
+                1,
+                getCTypeFor<decltype(&col[0])>(),
+                &col,
+                sizeof(col),
+                &col_ind
+            )
+        );
+
+        ++total_rows;
+    }
+
+    STOP_MEASURING_TIME_AND_REPORT(total_rows);
+
+    ASSERT_EQ(total_rows, total_rows_expected);
+}
+
 // API call that doesn't reach the driver, i.e., this is effectively (somewhat incomplete) Driver Manager overhead, just for the reference.
 TEST_F(PerformanceTest, ENABLE_FOR_OPTIMIZED_BUILDS_ONLY(UnimplementedAPICallOverhead)) {
     constexpr std::size_t call_count = 1'000'000;
```

You can run it using:
```
./driver/test/clickhouse-odbcw-client-it "ClickHouse DSN (Unicode)" --gtest_filter=PerformanceTest.UnicodeConverter
```

Meanwhile, this commit https://github.com/traceon/clickhouse-odbc/commit/b4ed4d899aea5fc7f03461e6eec63049814bb9f8 has changes that reuse `std::wstring_convert` instance (performance is similar to your code, in all platforms accordingly, just without `thread_local`, etc.), however it is just a step towards transition to using ICU for conversion, at least in Unix platforms, and maybe eventually in Windows too, if it proves to be faster and more correct.
