### ISSUE TITLE
Add log_queries=1 parameter to the connection string

### ISSUE THREAD

**Issue by vincenzon** [ClickHouse/clickhouse-odbc#229]
I am trying to set the log_queries parameter within the connection string. My attempt:

```
import pyodbc
import pandas as pd
con_str = 'Driver=/srv/jupyterlab/clickhouse-odbc/libclickhouseodbc.so;server=clickhouse;timeout=600;log_queries=1'
with pyodbc.connect(con_str, autocommit = True) as con:
    con.setencoding('utf-8')
    df = pd.read_sql("select 1", con)
```

But the parameter doesn't have any effect. Is it possible to set this parameter through the connection string?

**Comment by traceon** [comment]
Try specifying all/some connection-related info in the `url` parameter of Connection String/DSN, and then, in url, specify `log_queries`. Like:
```
...
timeout=600
url=https://default:password@clickhouse:8443/query?database=default&log_queries=1
...
```

**Comment by vincenzon** [comment]
@traceon that did the trick, thank you.

Matt
