### ISSUE TITLE
README.md doesn't reflect the most recent state of things

### ISSUE THREAD

**Issue by traceon** [ClickHouse/clickhouse-odbc#240]

**Comment by filimonov** [comment]
Fix build instructions (also for mac). Create 'how to collect debug information' section (enabling trace log for Windows/Mac / Linux). 

It can be a short info in readme, and detailed info with screenshots like here - in separate file.

Like here:
https://docs.oracle.com/cd/E17952_01/connector-odbc-en/connector-odbc-configuration-trace-windows.html
