### ISSUE TITLE
Integrate support of alternative wire protocols for communications between driver and data source (ClickHouse server)

### ISSUE THREAD

**Issue by traceon** [ClickHouse/clickhouse-odbc#242]
Motivated by potential performance gains. First protocol to integrate should be `RowBinaryWithNames`.

**Comment by filimonov** [comment]
Most probably `RowBinaryWithNamesAndTypes `

**Comment by alexey-milovidov** [comment]
How the performance of ODBC driver is evaluated?

**Comment by traceon** [comment]
Currently, we aim at 3 relatively independent parts that contribute to the overall performance:
1. Retrieving data from the server: the wire protocol (this issue.) This contributes to a latency associated with extracting data (converting string to double, integers etc.) from the wire.
2. Added cost of each ODBC API call. Currently application either
2.1. binds a single-row buffer for each column, and calls `SQLFetch` to get next row (addressing this with https://github.com/ClickHouse/clickhouse-odbc/issues/235 and then implementing `SQLFetchScroll`/`SQLExtendedFetch`)
2.2. or even worse, call `SQLGetData` for each column for each row (after a `SQLFetch`). So there are lots of api calls involved to read a row. To address the second scenario (and partially the first one), we plan to reduce the added cost of a single api call: the issue https://github.com/ClickHouse/clickhouse-odbc/issues/234

So to answer your original question: we are measuring the time from executing a query (from a C++ client code) until the result set is completely read, binding buffers buffers of same types to columns.

Query looks like this:
```
SELECT CAST('some not very long text', 'String') as col1, CAST('12345', 'Int') as col2, CAST('12.345', 'Float32') as col3, CAST('-123.456789012345678', 'Float64') as col4 FROM numbers(1000000)
```

(Now once I am writing this, I wonder, maybe we should start measuring right after the statement is executed, to remove prepare/execute steps from the measured time, but for big enough result set that shouldn't make any significant difference.)
