### ISSUE TITLE
System error code 126

### ISSUE THREAD

**Issue by radiatorius2048** [ClickHouse/clickhouse-odbc#251]
Error when adding ClickHouse source:
![image](https://user-images.githubusercontent.com/20090434/72519536-3a0a7080-3860-11ea-9a3a-c4583fbb921f.png)

**Comment by traceon** [comment]
Have you verified that the mentioned file exists at that location?

**Comment by radiatorius2048** [comment]
> Have you verified that the mentioned file exists at that location?

of course:
![image](https://user-images.githubusercontent.com/20090434/72530293-bf4d4f80-3877-11ea-965d-ab90d5eea7f6.png)

**Comment by traceon** [comment]
Try to:
1. uninstall `clickhouse-odbc`
2. make sure that `C:\Program Files\clickhouse-odbc` folder is removed
3. the following registry keys are removed:
    - `HKLM\SOFTWARE\ODBC\ODBCINST.INI\ClickHouse ODBC Driver (ANSI)`
    - `HKLM\SOFTWARE\ODBC\ODBC.INI\ClickHouse DSN (ANSI)`
    - `HKLM\SOFTWARE\ODBC\ODBCINST.INI\ClickHouse ODBC Driver (Unicode)`
    - `HKLM\SOFTWARE\ODBC\ODBC.INI\ClickHouse DSN (Unicode)`
4. install 64-bit `.msi` package
5. try adding DSN again

**Comment by radiatorius2048** [comment]
> Try to:
> 
> 1. uninstall `clickhouse-odbc`
> 2. make sure that `C:\Program Files\clickhouse-odbc` folder is removed
> 3. make sure that the following registry keys are removed:
>    
>    * `HKLM\SOFTWARE\ODBC\ODBCINST.INI\ClickHouse ODBC Driver (ANSI)`
>    * `HKLM\SOFTWARE\ODBC\ODBC.INI\ClickHouse DSN (ANSI)`
>    * `HKLM\SOFTWARE\ODBC\ODBCINST.INI\ClickHouse ODBC Driver (Unicode)`
>    * `HKLM\SOFTWARE\ODBC\ODBC.INI\ClickHouse DSN (Unicode)`

^ - there's nothing to do because the installer removes everything by itself.

> 4. install 64-bit `.msi` package
> 5. try adding DSN again
Nothing has changed, getting the same error. By the way, no problems with version 1.1.2 .

**Comment by traceon** [comment]
I am unable to reproduce that locally, that is, it works on my machine, the 1.1.3 installer.
Are you installing with runtime deps? (a separate component option in the installer; that may help)

**Comment by radiatorius2048** [comment]
We use standard settings:
![image](https://user-images.githubusercontent.com/20090434/72589707-a50d8300-3904-11ea-9393-f99d76d3b662.png)

I can't find anything specific in windows log:
Windows Installer installed the product. Product Name: clickhouse-odbc. Product Version: 1.1.3. Product Language: 1033. Manufacturer: Yandex LLC. Installation success or error status: 0.

How else could this error be debugged ?

**Comment by traceon** [comment]
Which version of Windows are you using?

**Comment by radiatorius2048** [comment]
> Which version of Windows are you using?

OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393

**Comment by filimonov** [comment]
VCRUNTIME140_1.DLL

![dep_walker](https://user-images.githubusercontent.com/1549571/72617650-bc1a9800-3939-11ea-9545-8f421622c22b.png)

**Comment by traceon** [comment]
Yup, seems very similar to this:

**Comment by traceon** [comment]
Doesn't installation folder have that `vcruntime140.dll` ?

**Comment by traceon** [comment]
Anyway, a quick solution would be manually installing x86 and x64 Visual Studio C++ Redistributable libraries from: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by filimonov** [comment]
![VCRUNTIME](https://user-images.githubusercontent.com/1549571/72618129-bec9bd00-393a-11ea-8c64-ada2f1629abf.png)

**Comment by radiatorius2048** [comment]
> Doesn't installation folder have that `vcruntime140.dll` ?
Lib vcruntime140.dll available in the installation folder: 
![image](https://user-images.githubusercontent.com/20090434/72618534-f852f600-3943-11ea-98f4-205901c2bb06.png)

After  x64 Visual Studio C++ Redistributable libraries installation error disappeared , good.

**Comment by traceon** [comment]
Thanks, we will work on making sure all needed runtime libs are redistributed.

**Comment by filimonov** [comment]
It looks like that bug is the reason for the issue: https://gitlab.kitware.com/cmake/cmake/issues/19829

I've added the note about vcredist to Release page for Windows users. If we will be able to fix the build, I will reupload it to Releases.

@radiatorius2048  thanks for a report and help with debugging the issue.

**Comment by vladimir77** [comment]
I encountered the same error (Windows 10, clickhouse-odbc Release 1.1.3.20200115). 

To fix this problem need to manually install 'Visual Studio C++ Redistributable' libs as described above:
> @traceon Anyway, a quick solution would be manually installing x86 and x64 Visual Studio C++ Redistributable libraries from: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
