### ISSUE TITLE
Tableau Embedded Credentials 

### ISSUE THREAD

**Issue by sablastik** [ClickHouse/clickhouse-odbc#262]
Hi!
Using Clickhouse ODBC DSN with Tableau doesn’t provide embedding connection credentials when publishing to Tableau Server.
Tableau Support says: "I made some internal repro on your behalf and I could verify that the Attributes are saved in Tableau Desktop 2019.4.3 with other data sources. We are not able to test ODBC from Clickhouse as it is beyond our scope."

**Comment by savelov** [comment]
you need either to embed credentials when publishing (
https://help.tableau.com/current/pro/desktop/en-us/publishing_sharing_authentication.htm),
or embed them later on the web interface of tableau server (
https://support.biconnector.com/support/solutions/articles/8000078385-how-to-embed-password-for-a-data-source-in-tableau-server-).
Please note that credentials will not be available if you will be editing
workbook by the user, different not from the owner of the workbook


чт, 20 февр. 2020 г. в 17:54, sablastik <notifications@github.com>:

**Comment by sablastik** [comment]
We are trying to embed them when publishing, however it doesn't happen. 
The steps to reproduce:
macOS 10.15.1 (19B88)
Tableau Desktop 2019.4.2

1. Open Other Databases (ODBC)
2. Select preconfigured DSN
![image](https://user-images.githubusercontent.com/16276988/75035524-b5df8480-54c0-11ea-8364-2d34b5dbbf53.png)
3. Use any table
4. Create Extract
5. Publish workbook to Tableau Server with "Allow refresh access" option (which should embed credentials)
![image](https://user-images.githubusercontent.com/16276988/75035814-66e61f00-54c1-11ea-9611-8987292114c7.png)
6. Open Data Source settings on Tableau Server - they are empty and it's impossible to make Extract refresh.
![image](https://user-images.githubusercontent.com/16276988/75035897-9e54cb80-54c1-11ea-9866-fdcb473b690f.png)

However, if I fill "Connection Attributes" manually at Step 2, then credentials will be embedded correctly, but they wouldn't be saved in the workbook.

**Comment by savelov** [comment]
In my case, credentials were entered (semi automatically, In Windows) at
step 2, hence they are available for Tableau and can be embedded.
If credentials are saved only inside DSN settings config, then they should
be configured similarly on server side and that way it can potentially
work. Tableau however does not have access to them in this case.




пт, 21 февр. 2020 г., 15:51 sablastik <notifications@github.com>:
