### ISSUE TITLE
Erlang odbc:param_query not working with Clickhouse ODBC driver

### ISSUE THREAD

**Issue by rom8726** [ClickHouse/clickhouse-odbc#27]
I tried to execute the query using Erlang ODBC client. This code not working:
```
odbc:start().
{ok, Ref} = odbc:connect("DSN=Clickhouse", []).
odbc:param_query(Ref, "SELECT * FROM test WHERE app_id = ?", [{sql_integer, [1]}]).
```
Error message:
```
{error,connection_closed}

=ERROR REPORT==== 21-Aug-2017::12:44:19 ===
ODBC: received unexpected info: {tcp_closed,#Port<0.541>}


=ERROR REPORT==== 21-Aug-2017::12:44:19 ===
** Generic server <0.79.0> terminating 
** Last message in was {#Port<0.539>,{exit_status,22}}
** When Server state == {state,#Port<0.539>,
                               {<0.77.0>,#Ref<0.2986369631.1162870785.139969>},
                               <0.77.0>,undefined,on,false,false,on,connected,
                               undefined,0,
                               [#Port<0.537>,#Port<0.538>],
                               #Port<0.540>,#Port<0.541>}
** Reason for termination == 
** {port_exit,could_not_bind_data_buffers}
```

But this code works correctly (without params):
```
odbc:param_query(Ref, "SELECT * FROM test WHERE app_id = 1", []). 
```

**Comment by artpaul** [comment]
Hi,
do you run it on Windows or on Linux?

**Comment by rom8726** [comment]
@artpaul Ubuntu 16.04 LTS

**Comment by artpaul** [comment]
I'm almost not familiar with Erlang, so can you provide a description how to install Erlang ODBC client or link to instruction about it?

**Comment by rom8726** [comment]
@artpaul ODBC client already included in Erlang platform.
You can install Erlang on Ubuntu following steps:

- Add Erlang Solutions repo: `wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb`
- Run: `sudo apt-get update`
- Install the Erlang/OTP platform and all of its applications: `sudo apt-get install esl-erlang`

Then you can use Erlang command line tool `erl` to run commands.

**Comment by rom8726** [comment]
Documentation for Erlang ODBC - http://erlang.org/doc/man/odbc.html
Examples - http://erlang.org/doc/apps/odbc/getting_started.html

**Comment by artpaul** [comment]
@om8726 I have reproduced the problem, thanks for the installation instruction.
The short answer is that client library calls SQLBindParameter method which currently is not implemented. I will fix it but before that you need to use string manipulation to form complete query.

**Comment by rom8726** [comment]
@artpaul Great! Thank you very much!

**Comment by millin** [comment]
@artpaul Do you plan to implement SQLBindParameter function?
CC @proller

**Comment by traceon** [comment]
Implemented in `master`, with some caveats.

**Comment by filimonov** [comment]
Please check https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.0.20191028
