### ISSUE TITLE
Power Bi + ClickHouse ODBC for DirectQuery mode

### ISSUE THREAD

**Issue by Alexeykhr** [ClickHouse/clickhouse-odbc#271]
Hello, Is it possible to use DirectQuery when working with Power BI Desktop?

I installed the driver and then added it as **ClickHouse Unicode**.

There are a couple of ODBC drivers on this list that support DirectQuery: Jethro ODBC, MarkLogic ODBC. This [Issue 89](https://github.com/ClickHouse/clickhouse-odbc/issues/89) says that **direct query mode** is used, but I have no choice when receiving the data.

In general, I saw that it is quite possible to make this mode for the ODBC driver, so is it possible to enable this mode? Or am I connecting the driver itself incorrectly? Or for this, you need to build the driver yourself?

![photo_2020-02-27_18-14-46](https://user-images.githubusercontent.com/14747569/75481409-af16ad00-59ab-11ea-92b9-5e71326d3e80.jpg)

**Comment by traceon** [comment]
As far as I understand DirectQuery should be supported by data source/connector: https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources

And for generic ODBC drivers it is not supposed to work. Hence, this driver cannot be used with DirectQuery.

**Comment by Alexeykhr** [comment]
Thanks for the answer, I will look for a solution :)

**Comment by gersmann** [comment]
@Alexeykhr I tested this by buidling a custom connector on top of clickhouse ODBC. It is not going to work, the way Clickhouse deals with aliases (they are global for a query) is not SQL-conformant and does not work with the SQL generated by powerquery.

**Comment by kutny** [comment]
Has someone tested https://github.com/belyaevvo/ClickHouseConnector ?
