### ISSUE TITLE
Низкая скорость работы с Tableau

### ISSUE THREAD

**Issue by sablastik** [ClickHouse/clickhouse-odbc#295]
При формировании экстрактов в Табло скорость выгрузки составляет порядка 8000 строк/с, тот же запрос через JDBC ~250 000/с. Может быть есть какой то параметр который стоит передать драйверу для увеличения скорости?

**Comment by traceon** [comment]
Вдобавок к настройке Prefetch Count в Tableau, на стороне драйвера необходима имплементация #235 и указанной там batch fetch функциональности.

**Comment by traceon** [comment]
Попробуете с новой версией драйвера?
https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.8.20200710

**Comment by nvm1** [comment]
@traceon , привет! Так же столкнулись с проблемой низкой скорости выгрузки из Tableau. Постараюсь на этой неделе проверить, как обстоят дела с 1.1.8.

PS Огромное спасибо за работу над драйвером, очень нужное дело делаете!

**Comment by nvm1** [comment]
@traceon , на тесте получилось выгрузить 5 млн строк за 37 секунд, т.е. около 135к строк в секунду.

**Comment by traceon** [comment]
@nvm1 а как было до этого? Еще имеет смысл изменить формат на RowBinaryWithNamesAndTypes, см. https://github.com/ClickHouse/clickhouse-odbc#url-query-string  есть особенности и корнер кейсы. Должно еще ускорить.

**Comment by nvm1** [comment]
@traceon, переустановил специально 1.1.7 и протестил. Тестил на двух разных кластерах (версии клика 19.7.6 и 19.5.2) на разных партах. В запросе было 17 колонок: 3 datetime, 5 date, 3 string, остальные Int/UInt.

На 1.1.7 4 запроса по 2 миллиона строк выгружались в среднем за 70 секунд (~ 28 571 строк в секунду)
На 1.1.8 4 запроса по 3 миллиона строк выгружались в среднем за 23 секунды (~ 130 434 строк в секунду)

RowBinaryWithNamesAndTypes ничего не добавил с точки зрения скорости выгрузки : результаты остались такие же, как и для ODBCDriver2 (тестил на 1.1.8)

**Comment by traceon** [comment]
Ясно. Спасибо! `RowBinaryWithNamesAndTypes` может быть медленнее на date/time, но должен быть быстрее на всем остальном. `ODBCDriver2` медленный на integers/floating points.

**Comment by nvm1** [comment]
@traceon будем знать :) Вам спасибо, х4 прирост в приозводительности - это очень круто.

**Comment by sablastik** [comment]
server - 19.7.5.27
не получилось проверить(
HTTP status code: 400 Received error: "10.0.5.4:56045": unsupported path: "/query"

**Comment by traceon** [comment]
`unsupported path: "/query"` - можно подправить DSN на supported path.

**Comment by sablastik** [comment]
> `unsupported path: "/query"` - можно подправить DSN на supported path.

что то я туплю, а что тут тогда должно быть?

**Comment by traceon** [comment]
Как выглядит DSN?

**Comment by sablastik** [comment]
> Как выглядит DSN?

[ClickHouse DSN (ANSI)]
Driver      = ClickHouse ODBC Driver (ANSI)
Description = DSN (localhost) for ClickHouse ODBC Driver (ANSI)

Proto = https
Server = ip
Port = 80
UID = логин
PWD = пароль
Database = default
Timeout=60

**Comment by traceon** [comment]
(Отсутствуещий) `Path` сейчас устанавливается по умолчанию в `/query`. Попробуйте что то типа `/`. Возможно, связано с настройками или версией сервера.
