### ISSUE TITLE
Не получается выгрузить данные из Clickhouse через SSIS пакет

### ISSUE THREAD

**Issue by AlexSD2000** [ClickHouse/clickhouse-odbc#296]
Clickhouse версии 20.3.8.53
Visual Studio 2019
odbc driver 1.1.7 x32 (win)
Настроил odbc driver - в SystemDSN добавил драйвер 32 bit (Clickhouse ODBC driver Unicode), указал хост, порт и базу.
Сделал простейший SSIS пакет. Забрать данные из ODBC Source и положить в SQL Server
При настройке ODBC Source проблем не было: таблица из Clickhouse видна, колонки ее видны и Preview работает - показывает данные из таблицы из Clickhouse

Но при собственно запуске пакета на выполнение из студии - ошибка на шаге "ODBC Source"

В логе Clickhouse есть вот такое:

2020.05.27 09:30:39.292148 [ 9891 ] {caad6f82-4855-4a5d-8c37-e26785d03153} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.8.53)

При включении трассировки odbc вот такое можно заметить:

DtsDebugHost    2d2c-3a94	EXIT  SQLExecute  with return code -1 (SQL_ERROR)
		HSTMT               0x08B35058
		DIAG [HY000] statement not prepared (1) 

Подскажите, пожалуйста, что можно сделать, чтобы отработал ssis пакет? Недонастроил я может быть что-то?

**Comment by traceon** [comment]
Две, на первый взгляд, несвязанные ошибки. Можно точную последовательность действий для воспроизведения?

**Comment by AlexSD2000** [comment]
1. Установка и настройка odbc драйвера

![image](https://user-images.githubusercontent.com/66003312/83113173-ee9a8580-a0cf-11ea-8545-2f06c45ebafe.png)

2. Visual Studio 2019. Создание нового SSIS пакета. Внизу, в "Connection managers" добавляем новое подключение: New Connection -> Type - ODBC

![image](https://user-images.githubusercontent.com/66003312/83113941-f6a6f500-a0d0-11ea-82f0-9cd545b1a3b8.png)

В "Data connections" видно созданное на первом шаге подключение, выбираем его

![image](https://user-images.githubusercontent.com/66003312/83114119-3a016380-a0d1-11ea-97c4-b1e497fd3844.png)


В SSIS пакете далее добавляем "Data flow task". Внутри "Data flow task" добавляем "ODBC Source"

![image](https://user-images.githubusercontent.com/66003312/83114374-8ea4de80-a0d1-11ea-8d43-0032c12db4b2.png)

При двойном клике по нему открывается "ODBC Source editor"
В выпадающем списке выбираем имя тестовой таблицы - myTestTable. 

![image](https://user-images.githubusercontent.com/66003312/83114608-d9265b00-a0d1-11ea-9a98-27b76841e4aa.png)

На вкладке "Columns" правильно видна одна колонка тестовой таблицы - UserID

![image](https://user-images.githubusercontent.com/66003312/83114745-0d9a1700-a0d2-11ea-8ac4-740da535b159.png)

При нажатии на кнопку "Preview" видны строки из тестовой таблицы Clickhouse

![image](https://user-images.githubusercontent.com/66003312/83114918-4a660e00-a0d2-11ea-8ce5-18545994d5a4.png)

Далее добавляем какой-нибудь "Destination" (таблица в SQL Server или просто текстовый файл). Я для теста выбрал таблицу в SQL Server

![image](https://user-images.githubusercontent.com/66003312/83115138-9e70f280-a0d2-11ea-920b-7e73d6cff579.png)

На данный момент вроде бы всё хорошо. Даже данные из Clickhouse видны в preview.
Но при запуске собственно пакета на исполнение (F5 в студии или Start) - падает ошибка на шаге "ODBC Source".

![image](https://user-images.githubusercontent.com/66003312/83115422-0293b680-a0d3-11ea-9f45-f3a2c356fba3.png)

Error: 0xC0014020 at Data Flow Task, ODBC Source [2]: SQLSTATE: HY000, Message: statement not prepared;

**Comment by traceon** [comment]
Дошли руки. Воспризвел. Проблема в том, что драйвер ошибочно разрушает prepared statements при `SQLFreeStmt(stmt, SQL_CLOSE)`.

Unrelated friendly reminder: используйте SSIS только с Unicode драйвером. Этой проблеме не поможет, однако, позволит извежать других. SSIS на данный момент 32-битный, т.е. и драйвер только 32-битный подойдет, но это вы уже учли.
