### ISSUE TITLE
Не могу подключиться через odbc к mssql через табличную фунцию odbc

### ISSUE THREAD

**Issue by Turum** [ClickHouse/clickhouse-odbc#297]
Доброго дня.
Добавьте пожалуйста в функцию передачу аргументов логина и пароля. Либо помогите разобраться с кейсом. 

FreeTDS driver
```

$  tsql -v -S QExport2 -U clickhouse -D QExport -p 1433 -P clickhouse
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting QExport as default database in login packet
Changed database context to 'QExport'.
Changed language setting to us_english.
1>
```
MSSQL driver
```

$ isql -v QExport clickhouse clickhouse
SQL>

```
FreeTDS DSN tabix/datagrip

```
select tadedate from odbc('DSN=QExport2','QExport','Orders')
         limit 100
[2020-05-28 14:57:40] Code: 86, e.displayText() = DB::Exception: Received error from remote server /columns_info?connection_string=DSN%3DQExport2&schema=QExport&table=Orders&external_table_functions_use_nulls=true. HTTP status code: 500 Internal Server Error, body: Error getting columns from ODBC 'Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Connection attempt failed: Connection:Not applicable
[2020-05-28 14:57:40] Server:QExport2
[2020-05-28 14:57:40] ===========================
[2020-05-28 14:57:40] ODBC Diagnostic record #1:
[2020-05-28 14:57:40] ===========================
[2020-05-28 14:57:40] SQLSTATE = 08S01
[2020-05-28 14:57:40] Native Error Code = 20009
[2020-05-28 14:57:40] [FreeTDS][SQL Server]Unable to connect: Adaptive Server is unavailable or does not exist
[2020-05-28 14:57:40] ===========================
[2020-05-28 14:57:40] ODBC Diagnostic record #2:
[2020-05-28 14:57:40] ===========================
[2020-05-28 14:57:40] SQLSTATE = 08001
[2020-05-28 14:57:40] Native Error Code = 0
[2020-05-28 14:57:40] [FreeTDS][SQL Server]Unable to connect to data source
[2020-05-28 14:57:40] ===========================
[2020-05-28 14:57:40] ODBC Diagnostic record #3:
[2020-05-28 14:57:40] ===========================
[2020-05-28 14:57:40] SQLSTATE = 01000
[2020-05-28 14:57:40] Native Error Code = 20013
[2020-05-28 14:57:40] [FreeTDS][SQL Server]Unknown host machine name.
[2020-05-28 14:57:40] (version 20.3.8.53)'
[2020-05-28 14:57:40] (version 20.3.8.53)

```

MSSQL DSN tabix/datagrip

```

default> select tadedate from odbc('DSN=QExport','QExport','Orders')
         limit 100
[2020-05-28 14:59:54] Code: 86, e.displayText() = DB::Exception: Received error from remote server /columns_info?connection_string=DSN%3DQExport&schema=QExport&table=Orders&external_table_functions_use_nulls=true. HTTP status code: 500 Internal Server Error, body: Error getting columns from ODBC 'Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Connection attempt failed: Connection:Not applicable
[2020-05-28 14:59:54] Server:Not applicable
[2020-05-28 14:59:54] ===========================
[2020-05-28 14:59:54] ODBC Diagnostic record #1:
[2020-05-28 14:59:54] ===========================
[2020-05-28 14:59:54] SQLSTATE = 28000
[2020-05-28 14:59:54] Native Error Code = 18456
[2020-05-28 14:59:54] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user ''.
[2020-05-28 14:59:54] (version 20.3.8.53)'
[2020-05-28 14:59:54] (version 20.3.8.53)
```
odbc.ini
```

[QExport]
Server      = 10.1.110.73
Database        = QExport
Driver          = MSSQL
Port            = 1433
uid             = clickhouse
password        = clickhouse
;Trace          = 1
;TraceFile      = /tmp/odbc_mssql.log
;ForceTrace     = yes

[QExport2]
Server      =  QExport2
Database        = QExport
Driver          = FreeTDS
Port            = 1433
uid            = clickhouse
password        = clickhouse


```

Спасибо.

**Comment by traceon** [comment]
> Добавьте пожалуйста в функцию передачу аргументов логина и пароля. Либо помогите разобраться с кейсом.

Что именно имеете ввиду? Интерактивный запрос логина/пароля? Обычно это odbc-клиенты делают, или можно в крайнем случае в DSN/Connection String вручную вписать (как у вас).

> FreeTDS DSN tabix/datagrip
> MSSQL DSN tabix/datagrip

Вроде не в драйвере ошибка.

> ```[2020-05-28 14:59:54] Code: 86, e.displayText() = DB::Exception: Received error from remote server /columns_info?connection_string=DSN%3DQExport&schema=QExport&table=Orders&external_table_functions_use_nulls=true. HTTP status code: 500 Internal Server Error, body: Error getting columns from ODBC 'Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Connection attempt failed: Connection:Not applicable`

**Comment by Turum** [comment]
Спасибо за подсказку. Не сообразил сразу как прописать логин с паролем в секцию dsn. В документации не описаны такие моменты, я смотрел этот пример https://clickhouse.tech/docs/ru/sql-reference/table-functions/odbc/#dicts-external_dicts_dict_sources-odbc.
Немного не обычно, но заработало так.
```
SELECT TOP 100	TradeDate
FROM odbc('DSN=QExport;Uid=clickhouse;Pwd=clickhouse;', 'dbo', 'Orders')
```
Не подскажите с обратной проблемой?
Из mssql через linked сервер достучаться до таблицы в clickhouse. В идеале иметь возможность выполнить insert into СLICKHOUSE select from mssql table.
Подключение создается, но при попытке выполнить селект к любой таблице
`select tradedate from [CLICKHOUSE_25].[default]..[Orders]`
получаю ошибку

```
Msg 7399, Level 16, State 1, Line 1
The OLE DB provider "MSDASQL" for linked server "CLICKHOUSE_25" reported an error. The provider did not give any information about the error.
Msg 7312, Level 16, State 1, Line 1
Invalid use of schema or catalog for OLE DB provider "MSDASQL" for linked server "CLICKHOUSE_25". A four-part name was supplied, but the provider does not expose the necessary interfaces to use a catalog or schema.

```
Спасибо.

**Comment by traceon** [comment]
ODBC Driver Manager trace помог бы разобраться.
См. https://github.com/ClickHouse/clickhouse-odbc#enabling-driver-manager-tracing-unixodbc о том, как включить.

**Comment by Turum** [comment]
[SQL.LOG](https://github.com/ClickHouse/clickhouse-odbc/files/4702238/SQL.LOG)

**Comment by traceon** [comment]
Это точно попытка использовать ClickHouse ODBC Driver?

**Comment by Turum** [comment]
да конечно.

**Comment by traceon** [comment]
Судя по трейсу, он даже не подключается к драйверу. Драйвер не имплементирует `SQLBrowseConnect`, а в трейсе клиент вызывает эту функцию. Скорее всего, не к тому драйверу коннектились, когда собирали этот трейс, иначе в нем были бы другие `*Connect*`, учитывая то, что что-то все же работает через драйвер, а значит и подключиться к нему было возможно.

**Comment by Turum** [comment]
[SQL.LOG](https://github.com/ClickHouse/clickhouse-odbc/files/4702608/SQL.LOG)

**Comment by traceon** [comment]
Все еще нет:
```
		DIAG [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) 
```
Неправильный DSN или неправильный/отсутствующий файл драйвера, ассоциированный с запрашиваемым DSN.

**Comment by Turum** [comment]
Вот тут точно что то написал.

[SQL.LOG](https://github.com/ClickHouse/clickhouse-odbc/files/4702722/SQL.LOG)


```
command ShowSql 352c-3730	EXIT  SQLDataSourcesW  with return code 0 (SQL_SUCCESS)
		HENV                0x166BE568
		UWORD                        1 <SQL_FETCH_NEXT>
		WCHAR *             0x11FFA038 [      21] "ClickHouse_25_Unicode"
		SWORD                      254 
		SWORD *             0x00B2E374 (21)
		WCHAR *             0x11FFA448 [      32] "ClickHouse ODBC Driver (Unicode)"
		SWORD                      254 
		SWORD *             0x00B2E378 (32)

command ShowSql 352c-3730	ENTER SQLDataSourcesW 
		HENV                0x166BE568
		UWORD                        1 <SQL_FETCH_NEXT>
		WCHAR *             0x11FFA038 
		SWORD                      254 
		SWORD *             0x00B2E374
		WCHAR *             0x11FFA448 
		SWORD                      254 
		SWORD *             0x00B2E378

command ShowSql 352c-3730	EXIT  SQLDataSourcesW  with return code 100 (SQL_NO_DATA_FOUND)
		HENV                0x166BE568
		UWORD                        1 <SQL_FETCH_NEXT>
		WCHAR *             0x11FFA038 
		SWORD                      254 
		SWORD *             0x00B2E374
		WCHAR *             0x11FFA448 
		SWORD                      254 
		SWORD *             0x00B2E378

```

**Comment by traceon** [comment]
Вижу `SQLBindCol` до подготовки Result set. Ответ анологичен этому: https://github.com/ClickHouse/clickhouse-odbc/issues/299#issuecomment-635973406

**Comment by Turum** [comment]
Понял, тогда вернусь к обратной задаче, вытянуть данные через mssql odbc в clickhouse.
При попытке выгрузить приблизительно 8млн строк выдает
Code: 159, e.displayText() = DB::Exception: Timeout exceeded: elapsed 100.160693118 seconds, maximum: 5 (version 20.3.8.53).
Можно как то увеличить таймаут или обойти эту ошибку?
Там где датасет формируется быстрее, выгрузка проходит без проблем.
Спасибо.

**Comment by Turum** [comment]
Ставлю Timеout 0 или 100000, обрывается немного позже, пишет code 159 elapsed 244 second и так же дропается.  30.05.2020, 00:05, "Denis Glazachev" <notifications@github.com>: Попробуйте увеличить значение параметра Timеout в DSN.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by traceon** [comment]
Это в другом направлении, как я понимаю. Тут ClickHouse ODBC Driver не задействован. Тут задействован MySQL ODBC Driver, а ClickHouse - ODBC Client (через свой odbc-bridge.) Вопрос скорее в главный репо ClickHouse.

**Comment by Turum** [comment]
Да все так, только MS SQL. Мне пересоздать issue там?

**Comment by traceon** [comment]
Да
