### ISSUE TITLE
Compilation fails when using latest versions of Visual Studio VS : 16.6.1 or VS 16.6.2

### ISSUE THREAD

**Issue by XavierQuiniou** [ClickHouse/clickhouse-odbc#300]
Compile command:

cmake --build. --config RelWithDebInfo

Error messages:
<pre>
...\source\repos\clickhouse-odbc\driver\utils\type_parser.cpp: fatal error C1001: Internal compiler error. [C:\Users\admin\source\repos\clickhouse-odbc\build\driver\test\clickhouse-odbc-
ut.vcxproj]
LINK: fatal error LNK1000: Internal error during IMAGE :: BuildImage [C:\Users\admin\source\repos\clickhouse-odbc\build\driver\test\clickhouse-odbc-ut.vcxproj]

...\source\repos\clickhouse-odbc\driver\utils\type_parser.cpp: fatal error C1001: Internal compiler error. [C:\Users\admin\source\repos\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
LINK: fatal error LNK1000: Internal error during IMAGE :: BuildImage [C:\Users\admin\source\repos\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
</pre>

See the attached file for more details.

In order to avoid getting bored, I reported the problem to MS support:
https://developercommunity.visualstudio.com/content/problem/1077431/fatal-error-c1001-internal-compiler-error-xxxxvcxp.html

Unfortunately, they ask me in return more information that I cannot produce.
(see url above)
[LOG.txt](https://github.com/ClickHouse/clickhouse-odbc/files/4785289/LOG.txt)

**Comment by traceon** [comment]
I wasn't able to reproduce it using `VS 16.6.2`.
You could try repairing your Visual Studio installation, just to make sure nothing got broken during recent upgrade: https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2019

After that, please try clean checkout, cmake configure, build.

**Comment by XavierQuiniou** [comment]
We are responsible for the problem.
After repairing our VS version 16.6.2 and having re-extracted the application from github,
its compilation has been successfully executed.
It therefore appears that we are the culprits.

Indeed, in order to trace the transformation of the requests we added a logger, by depositing two files (<code>SimpleLog.h, SimpleLog.cpp</code>) in the directory :
<tt>.. \ source \ repos \ clickhouse-odbc \ driver \ escaping</tt>
The <tt>escape_sequences.cpp</tt> file has been modified accordingly.

This being done, the problem resurfaced.

In the case of the version of VS 16.5.4, this practice was not a problem.

It is likely that the filing of the files is no longer sufficient and that the new files should be declared
in the application CMakeList.txt.

We need to improve our knowledge of Visual Studio and its compilation environment.

Sorry for bothering you
