### ISSUE TITLE
libicuuc.so.50 not found

### ISSUE THREAD

**Issue by chrystelletableau** [ClickHouse/clickhouse-odbc#308]
Hi, I tried a connection to Clickhouse DB  via this ODBC driver from Tableau Server on an Ubuntu distrib.
We have an error message from Tableau '... libclickhouseodbcw.so file not found'
![image](https://user-images.githubusercontent.com/32531947/89448208-89aa7e00-d757-11ea-8fb7-ea6b01d6fc4d.png)
and if we check dependancies via ldd libclickhouseodbcw.so 
   command response we see : **'libicuuc.so.50 => not found'**
But impossible to install the libicu as explained in your [documentation](https://github.com/ClickHouse/clickhouse-odbc#run-time-dependencies-debianubuntu) ... 
   command response we see : 'Unable to locate package libicu'
in fact [libicu packages available](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libicu&searchon=names) for Ubuntu
tried to install the libicu-dev package but not better ... 
Any workaround ?

**Comment by traceon** [comment]
This is described in release notes of https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.7.20200414
I suggest you to build the driver manually for your system. It is easy: https://github.com/ClickHouse/clickhouse-odbc/blob/master/README.md#building-from-sources-debianubuntu
