### ISSUE TITLE
Can't fetch strings over ClickHouse odbc driver

### ISSUE THREAD

**Issue by leotausanovic** [ClickHouse/clickhouse-odbc#315]
I'm trying to fetch data from Clickhouse over ClickHouse ODBC driver using MSSQL OPENROWSET command.
I successfully fetch numeric types, but not strings - here are examples:

- ANSI driver

Numeric -> success
<img width="264" alt="ANSI numeric example" src="https://user-images.githubusercontent.com/70977175/92608509-bf420a00-f2b5-11ea-9128-90d819afdd90.png">

String -> error
<img width="378" alt="ANSI character example" src="https://user-images.githubusercontent.com/70977175/92606178-f367fb80-f2b2-11ea-92b8-67705456ede5.png">

- UNICODE driver

Numeric -> success
<img width="261" alt="UNICODE numeric example" src="https://user-images.githubusercontent.com/70977175/92606305-15617e00-f2b3-11ea-8375-3570828615d0.png">

String -> error
<img width="401" alt="UNICODE character example" src="https://user-images.githubusercontent.com/70977175/92606355-1eeae600-f2b3-11ea-8fb8-2057475d9c4f.png">

ClickHouse version = 20.3.15
ODBC driver version = 1.1.8.20200710 (Windows 64 bit)
SQL.LOG file couldn't be generated (tried all the tricks - searching in different temp folders, machine trace, tampering with registry, but with no avail )

Thank you in advance

**Comment by filimonov** [comment]
> SQL.LOG file couldn't be generated 

Did you try this https://github.com/ClickHouse/clickhouse-odbc#enabling-driver-manager-tracing-mdacwdac-microsoftwindows-data-access-components ?

**Comment by leotausanovic** [comment]
Hi,

forgot to restart sql server svc after trace had started. :)

Here it is.

[SQL.LOG](https://github.com/ClickHouse/clickhouse-odbc/files/5202348/SQL.LOG)

**Comment by traceon** [comment]
Thanks, @leotausanovic.

This PR should address the issue: #300.

I haven't tested it in your specific environment, so if you can, please build the driver from that branch and tell me if it actually fixes the problem for you. If you can't build the driver yourself, let me know, I'll prepare a binary for you.

**Comment by leotausanovic** [comment]
Hi @traceon ,
could you be so kind to provide a binary?
Thank you in advance!

**Comment by traceon** [comment]
@leotausanovic sure, 32 or 64 bit?

**Comment by leotausanovic** [comment]
@traceon 64bit, pretty please :)

**Comment by traceon** [comment]
@leotausanovic Here you go: [clickhouse-odbc-1.1.8-win64.msi.zip](https://github.com/ClickHouse/clickhouse-odbc/files/5209420/clickhouse-odbc-1.1.8-win64.msi.zip)

**Comment by leotausanovic** [comment]
@traceon thx a lot, will revert you with test results during next week.

**Comment by leotausanovic** [comment]
Hi, here is 2nd round of testing, using version of ODBC driver provided last week.

Now we have elaborate error, and due to that I modifed my set of so-called "test cases" by adding fixed-length string example.

Here are results of this round:

- ANSI

String -> error
<img width="481" alt="ANSI character example round 2" src="https://user-images.githubusercontent.com/70977175/93099392-40c7dc80-f6a8-11ea-80bb-5c170e12b9b2.png">

Fixed Length String -> success
<img width="281" alt="ANSI fixed character example round 2" src="https://user-images.githubusercontent.com/70977175/93099560-6c4ac700-f6a8-11ea-99bf-9551f5b1b719.png">

Numeric -> success
<img width="261" alt="ANSI numeric example round 2" src="https://user-images.githubusercontent.com/70977175/93099641-88e6ff00-f6a8-11ea-9ce9-e2dc04c930df.png">


- UNICODE

String -> error
<img width="436" alt="UNICODE character example round 2" src="https://user-images.githubusercontent.com/70977175/93099835-c77cb980-f6a8-11ea-8310-6ff8fd27d6e9.png">

Fixed Length String -> success
<img width="346" alt="UNICODE fixed character example round 2" src="https://user-images.githubusercontent.com/70977175/93099910-dcf1e380-f6a8-11ea-806c-088d9d608130.png">

Numeric -> success
<img width="290" alt="UNICODE numeric example round 2" src="https://user-images.githubusercontent.com/70977175/93099946-e8dda580-f6a8-11ea-9b00-e55c1d3df630.png">

Note- fixed length string is translated on SQL Server side to varchar(length) where length is same as fixed length parameter used in the call of ClickHouse function.
Destination datatype is same (varchar) regardless of driver version used (ANSI/UNICODE).
Of course, data in SQL Server destination is right padded with empty spaces. 
Using such solution isn't always feasible in that way.

Here is SQL.LOG file

[SQL.LOG](https://github.com/ClickHouse/clickhouse-odbc/files/5219198/SQL.LOG)



So, we can say there is workaround. But it isn't always feasible - due to right padding of destination result set. 
It also complicates query building for our clients, especially if they just want to preliminary investigate data. 

It would be really nice if we could execute query like this one over odbc without errors:
<img width="423" alt="Issue Explanation" src="https://user-images.githubusercontent.com/70977175/93100243-3e19b700-f6a9-11ea-9feb-24a4af88a018.PNG">

Nevertheless - thank you very much for your effort and kind assistance!

**Comment by traceon** [comment]
That SQL.LOG doesn't contain the part where the driver returns "Requested conversion is not supported." So it is impossible to tell what kind of call caused this. Meanwhile, the original issue seems to be resolved, and this one is separate.

**Comment by leotausanovic** [comment]
Hi @traceon , I saw there is possibility of internal ClickHouse tracing (not standard SQL.LOG trace), maybe this would be helpful?

**Comment by traceon** [comment]
No, and this "Requested conversion is not supported."  actually not from the driver. You probably need to align column types.

**Comment by traceon** [comment]
https://stackoverflow.com/questions/10122693/wide-varchar-field-causes-requested-conversion-is-not-supported-error-using-op

**Comment by leotausanovic** [comment]
Yes, will do - thanks for your help!

**Comment by dashtimehran** [comment]
I have similar issue in retrieving String data type in php using odbc. I get Out of memory (allocated 8388608) (tried to allocate 18446744073709551613 bytes)

**Comment by traceon** [comment]
@dashtimehran what kind of issue exactly?

**Comment by gfody** [comment]
this issue is resolved but I haven't been able to fetch strings via openrowset, what's the workaround?
