### ISSUE TITLE
Проблема с Tableau.

### ISSUE THREAD

**Issue by bun4uk** [ClickHouse/clickhouse-odbc#318]
При работе с Custom Query в Tableau есть один очень неудобный момент.
Если SQL с синтаксической ошибкой, либо не рабочий – Tableau грузит его без остановки и не выдает ошибку о том, что запрос не компилируется. И приходиться убивать табло файл и начинать все сначала. 
Если SQL без синтаксических ошибок и написан правильно – Tableau не просто компилирует и собирает метадату, а обрабатывает весь запрос – а это сильно влияет на время выполнения команды. 
Раньше использовали вертику и там Custom queries создавались моментально. С кликхаусом это становится не очень удобно, к сожалению.
Возможно ли как-то настроить драйвер, чтобы создавать custom queries для tableau не дожидаясь прогрузки всего запроса?

**Comment by traceon** [comment]
При SQL с синтаксической ошибкой, мне Tableau выдает `HTTP status code: 400 Received error: ...` ошибку от сервера о плохом синтаксисе.

При SQL `SELECT * FROM hits_100m_obfuscated` на сервере `play-api.clickhouse.tech`, Custom SQL появляется сразу, и данные не извлекаются, если не нажать Update Now/Automatically Update.

Если возможно, опишите пошагово, что и как делать, и что не так, и как хочется, чтоб было, используя DSN, ссылающийся на сервер https://clickhouse.tech/docs/en/getting-started/playground/ например.

**Comment by bun4uk** [comment]
@traceon почему-то не получилось из-под Tableau подключиться к playground. Использовали нашу бд. 

Записали видео где видно как изменение SQL в custom query приводит к извлечению данных и долгой загрузке.
https://www.youtube.com/watch?v=91XXFb8kOgU

На втором видео видно как внесение ошибки в SQL приводит к бесконечной загрузке. 
https://www.youtube.com/watch?v=k9AUm6IbBfU

**Comment by traceon** [comment]
Единственную проблему, которую я увидел - это долгий Loading Metadata.

На втором видео вы не подождали пока это не завершится и Tableau не покажет строку с ошибкой от ClickHouse сервера.

Примерно так же будет если написать `SELECT 1`, и `SEL_x_ECT 1`.

**Comment by traceon** [comment]
https://community.tableau.com/s/question/0D54T00000C5nNn/tableau-taking-long-time-for-loading-metadata-while-creating-data-connection

https://community.tableau.com/s/question/0D54T00000C5bl7/connection-stuck-in-loading-metadata

**Comment by bun4uk** [comment]
спасибо, почитаю посты
p.s. на втором видео я не стал дожидаться ошибки сервера, так как она не приходит. Запрос грузится вечность и приходится закрывать табло-файл

**Comment by bun4uk** [comment]
@traceon 
пробую подключиться из Tableau к `play-api.clickhouse.tech`. При попытке :
```
An error occurred while communicating with Other Databases (ODBC)
Bad Connection: Tableau could not connect to the data source.
Error Code: B19090E0
SSL Exception: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed
```
Настройки DSN сейчас такие:
<img width="671" alt="CleanShot 2020-10-06 at 11 58 02@2x" src="https://user-images.githubusercontent.com/14631690/95180859-33939e80-07cb-11eb-8d14-bbf133014140.png">

Также пробовал дополнительно указать `Proto: https` и `SSLMode: allow`. Ошибка не пропала.
Где я мог ошибиться в конфиге?

**Comment by traceon** [comment]
@bun4uk какая версия драйвера?

**Comment by bun4uk** [comment]
@traceon 
последняя
`1.1.8.20200710`

**Comment by traceon** [comment]
cat ~/.odbc.ini
[ODBC]
Debug          = yes
DebugFile      = /Users/denis/dev/altinity/tmp/odbc-driver-manager-debug.log
Trace          = yes
TraceFile      = /Users/denis/dev/altinity/tmp/odbc-driver-manager-trace.log
# TraceLibrary =

[ODBC Data Sources]
ClickHouse DSN (ANSI)         = ClickHouse ODBC Driver (ANSI)
ClickHouse DSN (Unicode)      = ClickHouse ODBC Driver (Unicode)
ClickHouse DSN (ANSI, RBWNAT) = ClickHouse ODBC Driver (ANSI)
ClickHouse DSN (dev)          = ClickHouse ODBC Driver (ANSI)

[ClickHouse DSN (ANSI)]
Driver        = ClickHouse ODBC Driver (ANSI)
Description   = ClickHouse DSN (ANSI)
Url           = http://default:@localhost:8123/query?database=test
Timeout       = 3
DriverLog     = no
DriverLogFile = /Users/denis/dev/altinity/tmp/odbc-driver.log

[ClickHouse DSN (Unicode)]
Driver        = ClickHouse ODBC Driver (Unicode)
Description   = ClickHouse DSN (Unicode)
Url           = http://default:@localhost:8123/query?database=default
Timeout       = 3
DriverLog     = no
DriverLogFile = /Users/denis/dev/altinity/tmp/odbc-driver.log

[ClickHouse DSN (ANSI, RBWNAT)]
Driver        = ClickHouse ODBC Driver (ANSI)
Description   = ClickHouse DSN (ANSI)
Url           = http://default:@localhost:8123/query?database=default&default_format=RowBinaryWithNamesAndTypes
Timeout       = 3
DriverLog     = no
DriverLogFile = /Users/denis/dev/altinity/tmp/odbc-driver.log

[ClickHouse DSN (dev)]
Driver        = ClickHouse ODBC Driver (ANSI)
Description   = ClickHouse DSN (dev)
Url           = https://playground:clickhouse@play-api.clickhouse.tech:8443/query?database=system
Host          = play-api.clickhouse.tech
Port          = 8443
Path          = /query
Database      = system
Username      = playground
Password      = clickhouse
CALocation    = /usr/local/etc/openssl@1.1/cert.pem
Timeout       = 3
DriverLog     = no
DriverLogFile = /Users/denis/dev/altinity/tmp/odbc-driver.log
λ Caladan ~ → iusql "ClickHouse DSN (dev)"
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> SELECT 1
+----+

| 1  |

+----+

| 1  |
+----+

SQLRowCount returns 1
1 rows fetched

**Comment by traceon** [comment]
С драйвером с мастера:

```
$ cat ~/.odbc.ini
...
[ClickHouse DSN (dev)]
Driver        = ClickHouse ODBC Driver (ANSI)
Description   = ClickHouse DSN (dev)
Url           = https://playground:clickhouse@play-api.clickhouse.tech:8443/query?database=system
Host          = play-api.clickhouse.tech
Port          = 8443
Path          = /query
Database      = system
Username      = playground
Password      = clickhouse
CALocation    = /usr/local/etc/openssl@1.1/cert.pem
Timeout       = 3
$ iusql "ClickHouse DSN (dev)"
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> SELECT 1
+----+

| 1  |

+----+

| 1  |
+----+

SQLRowCount returns 1
1 rows fetched
```

**Comment by traceon** [comment]
@bun4uk  Скорее всего, вам нужно указать `CALocation    = /usr/local/etc/openssl@1.1/cert.pem` в DSN.

**Comment by bun4uk** [comment]
Спасибо! Получилось подключиться.

Я разобрался в каком случае зависает выполнение запроса с ошибкой в синтаксисе.
Если установить большой Timeout в DSN конфиге, то процессинг запроса не упадет до тех пор, пока не закончится таймаут.

Steps to reproduce:
* Установить Timeout = 1000 в DSN конфигурации
* Создать custom SQL в Tableau с следующим запросом и нажать OK: 
```
select * frommm hits_v1
```
* получаем модальное окно, которое будет грузится около 17 минут, и только потом выдаст ошибку. 
<img width="635" alt="CleanShot 2020-10-06 at 17 49 47@2x" src="https://user-images.githubusercontent.com/14631690/95218001-7cb01680-07fc-11eb-8310-21d2a13f868a.png">

* попытка нажать `Cancel` не поможет
<img width="635" alt="CleanShot 2020-10-06 at 17 51 14@2x" src="https://user-images.githubusercontent.com/14631690/95218137-a36e4d00-07fc-11eb-8921-a05b2b0bafbb.png">

**Comment by bun4uk** [comment]
Также проверил логи кликхауса. Кликхаус сразу же бросает exception после попытки выполнения неправильного запроса из окна `Edit Custom SQL`. В то время, как модальное окно в Tableau продолжает загрузку, пока не закончится Timeout, и только потом выдает ошибку.

Иными словами:
* Создаю Custom SQL с синтаксической ошибкой в 18:07:01 (в настройках DSN Timeout=1000)
* Появляется модальное окно с загрузкой и долго грузится
* Проверяю error.log – там есть информация о синтаксической ошибке в 18:07:01
* Возвращаюсь к Tableau – а там все еще загрузка в модальном окне (на часах 18:08:30)
* В 18:24 в модальном окне появляется сообщение об ошибке в синтаксисе запроса.

**Comment by traceon** [comment]
Ну это, собственно, та проблема с "loading metadata". Ссылки на обсуждения, почему это так работает в Табло я привел выше. Не думаю, что что-то можно сделать на уровне драйвера, чтоб обойти это.

**Comment by yurifal** [comment]
Создайте вот такой файл кастомизации ODBC соединения для Tableau 
по месту ~/.Documents/My Tableau Repository/Datasources/**clickhouse.tdc**

```
<?xml version='1.0' encoding='utf-8' ?>
<connection-customization class='genericodbc' enabled='true' version='18.1'>
    <vendor name='ClickHouse' />
    <driver name='ClickHouse Driver' />
    <customizations>
        <customization name='CAP_CONNECT_STORED_PROCEDURE' value='no' />
        <customization name='CAP_CREATE_TEMP_TABLES' value='no' />
        <customization name='CAP_QUERY_GROUP_BY_ALIAS' value='no' />
        <customization name='CAP_QUERY_GROUP_BY_DEGREE' value='no' />
        <customization name='CAP_QUERY_INOUT_JOINS' value='no' />
        <customization name='CAP_QUERY_JOIN_PUSH_DOWN_CONDITION_EXPRESSIONS' value='yes' />
        <customization name='CAP_QUERY_JOIN_REQUIRES_SUBQUERY' value='yes' />
        <customization name='CAP_QUERY_SORT_BY_DEGREE' value='no' />
        <customization name='CAP_QUERY_WHERE_FALSE_METADATA' value='yes' />
        <customization name='CAP_SELECT_INTO' value='no' />
        <customization name='CAP_SELECT_TOP_INTO' value='no' />
    </customizations>
</connection-customization>

```
и перезапустите Tableau Desktop.

**Comment by traceon** [comment]
@yurifal Спасибо, тут исправление проблемы с метадатой или еще что-то?

Добавлю, что `<driver name='ClickHouse Driver' />` должен точно совпадать с именем драйвера, для которого создан используемый DSN.

**Comment by yurifal** [comment]
> @yurifal Спасибо, тут исправление проблемы с метадатой или еще что-то?
> 

по моим представлениям вот эта настройка добавляет в метадата-запросы нужный WHERE:

`        <customization name='CAP_QUERY_WHERE_FALSE_METADATA' value='yes' />
`


Три настройки ("стандартные" для ODBC драйверов многих других СУБД) 
явно запрещают создание времянок и операции с ними: 

```
        <customization name='CAP_CREATE_TEMP_TABLES' value='no' />
        <customization name='CAP_SELECT_INTO' value='no' />
        <customization name='CAP_SELECT_TOP_INTO' value='no' />

```


Остальные настройки взяты из файла, который уже есть в проекте: 

https://github.com/ClickHouse/clickhouse-odbc/blob/master/packaging/clickhouse-odbc.tdc.sample

**Comment by bun4uk** [comment]
@yurifal Спасибо!
Добавил этот файл, как вы описали. Имя драйвера указал своё. К сожалению, не не увидел изменений. Попытка ввода SQL с синтаксической ошибкой ждет окончания таймаута, перед показом самой ошибки.

![CleanShot 2020-10-07 at 11 10 26@2x](https://user-images.githubusercontent.com/14631690/95305098-34d9cf80-088e-11eb-9d3b-02c261506a23.png)
<img width="406" alt="CleanShot 2020-10-07 at 11 13 05@2x" src="https://user-images.githubusercontent.com/14631690/95305117-3a371a00-088e-11eb-9ae0-9dcd89fd0043.png">
<img width="655" alt="CleanShot 2020-10-07 at 11 17 22@2x" src="https://user-images.githubusercontent.com/14631690/95305498-b9c4e900-088e-11eb-9cfd-b6d5b483ea37.png">

**Comment by yurifal** [comment]
1) в логе Табло (в папке Logs файл log.txt) есть ли вот такой текст 

`found **matching** TDC `

?  Если есть -- то OK. Если нет -- значит TDC не подтягивается, 
и тогда нужно пере-проверять имя драйвера. 

2) Какой timeout выставлен в odbc.ini ? у меня 3 (секунды).
Если взять Ваш пример, то у меня через секунд 5 вываливается вот такая ошибка: 

<img width="614" alt="Screenshot 2020-10-07 at 13 55 34" src="https://user-images.githubusercontent.com/2496788/95322418-20ed9800-08a5-11eb-958d-981cba4c419e.png">

**Comment by bun4uk** [comment]
@yurifal 
в log.txt видно что TDC подтянулся.
```
{"ts":"2020-10-07T11:07:46.310","pid":91705,"tid":"c3997e","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"Found matching TDC '/Users/bunchukv/Documents/My Tableau Repository/Datasources/clickhouse.tdc' for class='genericodbc', vendor='ClickHouse', and driver='clickhouse'."}
```

Таймаут стоит 1000. Меньше не можем поставить, так как есть запрос от аналитиков. Соотсветсвенно ошибка (такая как вы в показали скриншоте) появляется где-то на 1005ой секунде, что ну очень неудобно. Хотя, если посмотреть логи самого кликхауса, то там эта ошибка появляется сразу же после попытки создать Custom SQL.

**Comment by yurifal** [comment]
Если Custom SQL синтаксически правильный, 
то Табло возвращает контроль сразу.

Может на этапе создания / правки источников 
(для работы в Data Pane с Custom SQL) 
использовать копию DSN но с Timeout = 3 
(или сколько будет удобно для отладки кода), 
а потом в prod сменить DSN и публиковать?

**Comment by bun4uk** [comment]
@yurifal 
Спасибо большое!
Такой вариант, в принципе, +- примелим.
Немного иначе правда сделали. 
В настройках DSN оставил Timeout=1000. А в конфиге соединения для Табло руками прописали Timeout=10. Для этапа создания Custom SQL этого достаточно.
![CleanShot 2020-10-07 at 15 13 40@2x](https://user-images.githubusercontent.com/14631690/95329531-c7d73180-08af-11eb-8358-932b6cc78877.png)

**Comment by dmserg** [comment]
Это кстати легко воспроизводится из test\test.py скрипта. Достаточно добавить в connection string у pyodbc.connect  ";TIMEOUT=300" и выполнить запрос 
`query("select * from system.nonexisting")`

Скрипт будет висеть 5 минут, в драйвере залипает вызов SQLFreeStmt.

**Comment by dmserg** [comment]
У меня получилось пофиксать эту проблему - https://github.com/ClickHouse/clickhouse-odbc/pull/326
Проверял через pyodbc и на Tableau. 
Посмотрите плз - нет ли тут еще каких-то подводных камней?

**Comment by filimonov** [comment]
> Это кстати легко воспроизводится из test\test.py скрипта. Достаточно добавить в connection string у pyodbc.connect ";TIMEOUT=300" и выполнить запрос
> `query("select * from system.nonexisting")`
> 
> Скрипт будет висеть 5 минут, в драйвере залипает вызов SQLFreeStmt.

Может быть попробуете добавить такой тест?

**Comment by dmserg** [comment]
> Может быть попробуете добавить такой тест?
В виде питон скрипта легко, а в интеграционных gtest тесты пока не нашел как легко это воспроизвести - в существующем тестовом фреймворке метод closeCursor() никогда не заходит в условие `if (connection.session && response && in)`. 
Но это легко воспроизводится в связке с ODBC клиентом - например Tableau или pyodbc.

**Comment by filimonov** [comment]
Да, у нас уже есть тесты в питоне - можно добавить туда 
https://github.com/ClickHouse/clickhouse-odbc/blob/master/test/test.py

**Comment by dmserg** [comment]
Кстати интересное наблюдение - это не воспроизводится если делать для pyodbc явный вызов connection.close(), но воспроизводится если оставить очистку ресурсов через __exit__ (на выходе контекста with) либо при окончании выполнения скрипта. Что наводит на мысли о не очень корректном обращении с коннекшеном в Tableau.

**Comment by dmserg** [comment]
> Да, у нас уже есть тесты в питоне - можно добавить туда
> https://github.com/ClickHouse/clickhouse-odbc/blob/master/test/test.py
> https://github.com/ClickHouse/clickhouse-odbc/tree/master/test/parameterized

добавленный тест понятен, подходит?

**Comment by filimonov** [comment]
> > Да, у нас уже есть тесты в питоне - можно добавить туда
> > https://github.com/ClickHouse/clickhouse-odbc/blob/master/test/test.py
> > https://github.com/ClickHouse/clickhouse-odbc/tree/master/test/parameterized
> 
> добавленный тест понятен, подходит?

Да, все выглядит хорошо. Спасибо!
