### ISSUE TITLE
Проблема при подключении Visual Studio 2019 к ClickHouse ODBC

### ISSUE THREAD

**Issue by BeHappy911** [ClickHouse/clickhouse-odbc#328]
Добрый день, не получилось настроить подключение в проекте с ClickHouse.
У меня есть пользовательский (ODBC), но увы его не видит Visual Studio 2019 :/
Прошу подсказать:
- Как я могу исправить это?
- Или есть другой способ?

https://b.radikal.ru/b09/2011/b8/bdf11a6e8f53.jpg

https://b.radikal.ru/b06/2011/dc/20fc3735870b.jpg

https://d.radikal.ru/d14/2011/a9/89ad96a4fd45.jpg

С уважением, Юрий.

**Comment by traceon** [comment]
Скорее всего, нужен 32-битный драйвер с его DSN. Также лучше использовать Unicode версию.

**Comment by BeHappy911** [comment]
`        Dim Conn1 As Object
        Dim rst As Object
        Dim sqlstring$, a$
        Dim test2 As VariantType

        rst = CreateObject("ADODB.Recordset")
        Conn1 = CreateObject("ADODB.Connection")

        a = "Driver={ClickHouse ODBC Driver (Unicode)};" &
               "URL=.mdb.yandexcloud.net; PORT=8443; DATABASE=DP_Analytics; uid= ; pwd=; SSLMode = Allow;" &
               "option=3"
        Conn1.ConnectionString = a
        Conn1.Open

        sqlstring$ = "Select * from DP_Analytics.Test2"
        rst.Open(sqlstring, Conn1)

        test2 = rst.Getrows
        Globals.Лист1.Cells(1, 1) = test2`
В ответ идет: "Refuse"

**Comment by BeHappy911** [comment]
Драйвер 32 битный - успешно установил, но подключиться пока не удалось:
https://d.radikal.ru/d00/2011/40/c9a5d4c06eb6.jpg
https://c.radikal.ru/c12/2011/23/7ea5fbf8814e.jpg
https://d.radikal.ru/d43/2011/e6/f185183b868b.jpg

**Comment by BeHappy911** [comment]
Спасибо, все получилось!
