### ISSUE TITLE
unresolved run-time dependencies on ubuntu

### ISSUE THREAD

**Issue by AndrewNik** [ClickHouse/clickhouse-odbc#332]
Hello. 
I am trying to use UnixODBC with this driver on Ubuntu (18.04). In README says that I shoud install "libicu" package, but it's only "libicu-dev" in ubuntu repo. I have downloaded latest library version (1.1.8) from "Releases" and noticed that it depends from libicuuc.so.50 (which didn't installed with libicu-dev). 
Because of this unixODBC says:
`[01000][unixODBC][Driver Manager]Can't open lib '/home/ubu/Downloads/clickhouse-odbc-1.1.8-Linux/lib64/libclickhouseodbc.so' : file not found
`
 I just have libicuuc.so, libicuuc.so.55 and higher on my OS. 
Can you build from source with these libs, or maybe you can give me link where I can download correct libs?

![image](https://user-images.githubusercontent.com/6717475/99882688-6981ca80-2c33-11eb-9d1a-c975a57e7b6c.png)

**Comment by traceon** [comment]
Please, see notes to https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.7.20200414

**Comment by AndrewNik** [comment]
Ok, I am trying to build it from source, but recieved this error.
![image](https://user-images.githubusercontent.com/6717475/99886375-0c930e00-2c4d-11eb-9e21-d1dde24172a9.png)
Any ideas how to fix it?

If I tryi to continue building and execute this one: 
`cmake --build . --config RelWithDebInfo`
I get next errors:
![image](https://user-images.githubusercontent.com/6717475/99886430-89be8300-2c4d-11eb-880a-b43283c94381.png)

**Comment by traceon** [comment]
> Ok, I am trying to build it from source, but recieved this error.

That's not a problem.

>  I get next errors:

These are strange, what compiler and linker are you using, which versions?

**Comment by AndrewNik** [comment]
I am using: cmake version 3.19.0, clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final), gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Before building I have removed default cmake (it's version was lower than need), and installed new  `sudo snap install cmake --classic`

**Comment by AndrewNik** [comment]
I fixed it just by installing cmake from "Kitware APT Repository". Thank you for answers, library was built successfully. 
Hope that i could use it in UnixODBC))
