### ISSUE TITLE
Проблема Power BI 

### ISSUE THREAD

**Issue by IvanSolovev** [ClickHouse/clickhouse-odbc#337]
к сожалению не удалось из Power Query загрузить таблицу в модель данных Power BI 
при загрузке данных выходит ошибка (таблица которую гружу не большая несколько десятков тысяч строк, таблицу менее 1 тыс строк загрузить удалось без ошибок)
Не удалось сохранить изменения на сервере. Возвращена ошибка "Ошибка OLE DB или ODBC: [DataSource.Error] ODBC: ERROR [HY000] bad conversion.".

все делал по статье 
https://medium.com/@annu.nmit/connecting-to-clickhouse-database-server-from-power-bi-864e950d83e2

Соловьев Иван
i.soloviev@rbk.money

**Comment by traceon** [comment]
Попробуйте локализовать колонку и примерно строку, в которой данные, вызывающие `bad conversion`.

**Comment by traceon** [comment]
Проблема, скорее всего, в каком-то экзотическом/ошибочном Unicode символе.

**Comment by IvanSolovev** [comment]
> Проблема, скорее всего, в каком-то экзотическом/ошибочном Unicode символе.

не понятно как это исправить...так как Power Queru сразу смотрит на всю таблицу и по шагам ее изменяет...поэтому если в начальной таблице ошибка - то весь запрос падает.

**Comment by IvanSolovev** [comment]
колонка с ошибкой не понятна

**Comment by traceon** [comment]
Нужен запрос, берущий каждый раз только одну колонку (или половину из списка потенциальных с ошибкой). И так пока не сведется к одной. Имеет смысл брать только строковые колонки.

**Comment by UnamedRus** [comment]
Похоже данная проблема возникает с колонкой FixedString.

**Comment by traceon** [comment]
Без steps/data to reproduce, я ничем не смогу помочь. Известных проблем с FixedString - нет.
