### ISSUE TITLE
Tableau Server UI not detecting clickhouse odbc data source

### ISSUE THREAD

**Issue by stephenpaul2727** [ClickHouse/clickhouse-odbc#342]
Hi All,

Thanks for this useful integration. 

Regarding my issue:

**Problem:**:

I had cloned this clickhouse-odbc project onto a new VM (centos 7) which also has tableau server running `Tableau Server Version: 2020.4.1 (20204.21.0114.0916) 64-bit Linux` .  Followed the instructions to make and generate the files. configured /etc/odbcinst.ini as follows:
```
[ODBC Drivers]  
ClickHouse=Installed  
UsageCount=1  

[ClickHouse]  
Description=ODBC Driver for ClickHouse  
Driver=/opt/clickhouse-odbc/build/driver/libclickhouseodbc.so  
Setup=/opt/clickhouse-odbc/build/driver/libclickhouseodbc.so  
UsageCount=1  
```
configured /etc/odbc.ini as below:
```
[ODBC Data Sources]  
Clickhouse=ClickHouse  
   
[Clickhouse]  
Driver=ClickHouse  
Description=My Clickhouse  
#Skipping server info  
`
Configured the clickhouse.tdc file at tabsvc/vizqlserver/Datasources/clickhouse.tdc as follows:
`

```
<connection-customization class='genericodbc' enabled='true' version='18.1'>  
<vendor name='Clickhouse' />  
<driver name='ClickHouse' />  
    <customizations>  
        <customization name='CAP_CONNECT_STORED_PROCEDURE' value='no' />  
        <customization name='CAP_QUERY_GROUP_BY_ALIAS' value='no' />  
        <customization name='CAP_QUERY_INOUT_JOINS' value='no' />  
        <customization name='CAP_QUERY_JOIN_PUSH_DOWN_CONDITION_EXPRESSIONS' value='yes' />  
        <customization name='CAP_QUERY_JOIN_REQUIRES_SUBQUERY' value='yes' />  
        <customization name='CAP_QUERY_SORT_BY_DEGREE' value='no' />  
    </customizations>  
</connection-customization>
```

Restarted tableau server with tsm restart
Checked whether the log detecting new tdc file is logged:
`
{"ts":"2021-01-27T04:16:52.678","pid":40033,"tid":"ad30","sev":"info","req":"-","sess":"-","site":"-","user":"-","k":"msg","v":"Found TDC '/opt/tableau/tableau-data/data/tabsvc/vizqlserver/Datasources/Clickhouse.tdc'."}
`
**Expected output:**
After tsm restart and logging into tableau UI, i expected to see the new data source in the tableau new workbook page.

**Obtained output:**
![image](https://user-images.githubusercontent.com/21348747/105953400-faa46180-6027-11eb-8b4e-a31d0c14a26c.png)

Could you advise what i might be missing?

Thanks again,...

**Comment by traceon** [comment]
Make sure that the driver is able to load in that environment.
Try
```sh
ldd /opt/clickhouse-odbc/build/driver/libclickhouseodbc.so
```
on the Tableau server side, on behalf the same user as the Tableau process is running from, in the same environment (specifically, check for `LD_LIBRARY_PATH` env var, that can be set for you Tableau server; use it for that `ldd` too.)

**Comment by stephenpaul2727** [comment]
Well, I think ldd is detecting the shared libraries
```
[root@rc ~]# ldd /opt/clickhouse-odbc/build/driver/libclickhouseodbc.so
        linux-vdso.so.1 =>  (0x00007ffc0e4b9000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff049bde000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ff0499d6000)
        libodbcinst.so.2 => /lib64/libodbcinst.so.2 (0x00007ff0497c4000)
        libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007ff04944b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ff049247000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff048f3f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff048c3d000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff048a27000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff048659000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff04a4bd000)
        libltdl.so.7 => /lib64/libltdl.so.7 (0x00007ff04844f000)
        libicudata.so.50 => /lib64/libicudata.so.50 (0x00007ff046e7c000)
[root@rc ~]# su - tableau -c "ldd /opt/clickhouse-odbc/build/driver/libclickhouseodbc.so"
        linux-vdso.so.1 =>  (0x00007ffe3e089000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7f1ae61000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f7f1ac59000)
        libodbcinst.so.2 => /lib64/libodbcinst.so.2 (0x00007f7f1aa47000)
        libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007f7f1a6ce000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f7f1a4ca000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7f1a1c2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f7f19ec0000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7f19caa000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f7f198dc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7f1b740000)
        libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f7f196d2000)
        libicudata.so.50 => /lib64/libicudata.so.50 (0x00007f7f180ff000)
```
So i think tableau user had access to load the shared libraries. The issue persists though. Any log files in particular we can check maybe?

**Comment by traceon** [comment]
As far as I remember, Tableau server uses a bundled version of `libstdc++`, which may not be compatible with the driver. Can you look at tableau logs to see if this is the case? (Unresolved symbols when loading the driver binary)

If it is true, the you will need to rebuild the driver with runtime linked statically:
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCH_ODBC_RUNTIME_LINK_STATIC=ON ..
```

**Comment by alexander-chashnikov** [comment]
You need to publish clickhouse data source from Tableau Desktop first. From Web you can't create a new data source from clickhouse.

**Comment by stephenpaul2727** [comment]
Resolving the issue as @alexander-chashnikov mentioned, the only way to publish a third party DS to tableau server is through tableau desktop which is weird in my opinion, but that is tableau i guess :)
