### ISSUE TITLE
Error while building on Mac

### ISSUE THREAD

**Issue by mirajgodha** [ClickHouse/clickhouse-odbc#345]
Getting error while building on MAC OS Catalina 10.15.7

- Hi Initially i got this error, the below error regarding subdirectories does not contain a CMakeLists.txt file. So, I copied the `clickhouse-odbc/CMakeLists.txt` to `clickhouse-odbc/contrib/ssl` and `clickhouse-odbc/contrib/poco` subdirectories path manually.

> (base) miraj@Miraj-13inch-mac build % cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl -DICU_ROOT=$(brew --prefix)/opt/icu4c ..
>  The C compiler identification is AppleClang 12.0.0.12000032
>  The CXX compiler identification is AppleClang 12.0.0.12000032
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMAKE_BUILD_TYPE: RelWithDebInfo
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
> -- Found Threads: TRUE
> -- Found iODBC: TRUE
> -- Using ODBC: iODBC
> -- 	ODBC_DIR=/usr/local/Cellar/libiodbc/3.52.13
> -- 	ODBC_CONFIG_SCRIPT=/usr/local/bin/iodbc-config
> -- 	ODBC_IODBC_IODBCTEST=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctest
> -- 	ODBC_IODBC_IODBCTESTW=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctestw
> -- 	ODBC_APP_DEFINES=
> -- 	ODBC_APP_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_APP_COMPILER_FLAGS=
> -- 	ODBC_APP_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbc
> -- 	ODBC_DRIVER_DEFINES=
> -- 	ODBC_DRIVER_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_DRIVER_COMPILER_FLAGS=
> -- 	ODBC_DRIVER_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbcinst
> -- Found ODBC: TRUE
> -- Found the following ICU libraries:
> --   uc (required)
> -- Found ICU: /usr/local/opt/icu4c/include (found version "67.1")
> CMake Error at contrib/CMakeLists.txt:21 (add_subdirectory):
>   The source directory
> 
>     /Users/miraj/Downloads/clickhouse-odbc/contrib/ssl
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at contrib/CMakeLists.txt:54 (add_subdirectory):
>   The source directory
> 
>     /Users/miraj/Downloads/clickhouse-odbc/contrib/poco
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at contrib/CMakeLists.txt:67 (add_library):
>   add_library cannot create ALIAS target "Poco::Net" because target "Net"
>   does not already exist.
> 
> 
> CMake Error at contrib/CMakeLists.txt:68 (add_library):
>   add_library cannot create ALIAS target "Poco::Foundation" because target
>   "Foundation" does not already exist.
> 
> 
> CMake Error at contrib/CMakeLists.txt:69 (add_library):
>   add_library cannot create ALIAS target "Poco::Util" because target "Util"
>   does not already exist.
> 
> 
> CMake Error at contrib/CMakeLists.txt:72 (set_property):
>   set_property could not find TARGET Net.  Perhaps it has not yet been
>   created.
> 
> 
> CMake Error at contrib/CMakeLists.txt:73 (set_property):
>   set_property could not find TARGET Foundation.  Perhaps it has not yet been
>   created.
> 
> 
> CMake Error at contrib/CMakeLists.txt:116 (add_subdirectory):
>   The source directory
> 
>     /Users/miraj/Downloads/clickhouse-odbc/contrib/googletest
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at contrib/CMakeLists.txt:121 (set_target_properties):
>   set_target_properties Can not find target to add properties to: gtest
> 
> 
> CMake Error at contrib/CMakeLists.txt:122 (set_target_properties):
>   set_target_properties Can not find target to add properties to: gtest_main
> 
> 
> CMake Error at contrib/CMakeLists.txt:123 (set_target_properties):
>   set_target_properties Can not find target to add properties to: gmock
> 
> 
> CMake Error at contrib/CMakeLists.txt:124 (set_target_properties):
>   set_target_properties Can not find target to add properties to: gmock_main
> 
> 
> CMake Error at contrib/CMakeLists.txt:140 (add_subdirectory):
>   The source directory
> 
>     /Users/miraj/Downloads/clickhouse-odbc/contrib/nanodbc
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at contrib/CMakeLists.txt:142 (set_target_properties):
>   set_target_properties Can not find target to add properties to: nanodbc
> 
> 
> -- clickhouse-odbc: ANSI
> -- clickhouse-odbcw: Unicode
> install_driver(ODBC) failed: Can't locate DBD/ODBC.pm in @INC (you may need to install the DBD::ODBC module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at (eval 8) line 3.
> Perhaps the DBD::ODBC perl module hasn't been fully installed,
> or perhaps the capitalisation of 'ODBC' isn't right.
> Available drivers: DBM, ExampleP, File, Gofer, Proxy, SQLite, Sponge.
>  at /Users/miraj/Downloads/clickhouse-odbc/test/detect_driver_manager.pl line 11.
> -- ODBC Driver Manager used by Perl's DBD::ODBC:
> Traceback (most recent call last):
>   File "/Users/miraj/Downloads/clickhouse-odbc/test/detect_driver_manager.py", line 5, in <module>
>     import pyodbc
> ImportError: No module named pyodbc
> -- ODBC Driver Manager used by Python 2's pyodbc:
> -- ODBC Driver Manager used by Python 3's pyodbc: unixODBC
> -- Testing with:
> 	TEST_DSN_LIST=ClickHouse DSN (ANSI);ClickHouse DSN (Unicode)
> 	PERL=/usr/bin/perl
> 	PERL_USES_MDAC=0
> 	PERL_USES_UNIXODBC=0
> 	PERL_USES_IODBC=0
> 	PYTHON2=/usr/bin/python2
> 	PYTHON2_USES_MDAC=0
> 	PYTHON2_USES_UNIXODBC=0
> 	PYTHON2_USES_IODBC=0
> 	PYTHON3=/Users/miraj/opt/anaconda3/bin/python3
> 	PYTHON3_USES_MDAC=0
> 	PYTHON3_USES_UNIXODBC=1
> 	PYTHON3_USES_IODBC=0
> 	ODBC_UNIXODBC_ISQL=
> 	ODBC_UNIXODBC_IUSQL=
> 	ODBC_IODBC_IODBCTEST=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctest
> 	ODBC_IODBC_IODBCTESTW=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctestw
> 	SQLCMD=SQLCMD-NOTFOUND
> -- Configuring incomplete, errors occurred!
> See also "/Users/miraj/Downloads/clickhouse-odbc/build/CMakeFiles/CMakeOutput.log".

- Then i got the errors in include, as below, which i fixed by putting the full path in include of these files `contrib/ssl/CMakeLists.txt` and `cmake/Modules/FindiODBC.cmake` files.

> (base) miraj@Miraj-13inch-mac build % cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl -DICU_ROOT=$(brew --prefix)/opt/icu4c ..
> -- CMAKE_BUILD_TYPE: RelWithDebInfo
> -- Using ODBC: iODBC
> -- 	ODBC_DIR=/usr/local/Cellar/libiodbc/3.52.13
> -- 	ODBC_CONFIG_SCRIPT=/usr/local/bin/iodbc-config
> -- 	ODBC_IODBC_IODBCTEST=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctest
> -- 	ODBC_IODBC_IODBCTESTW=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctestw
> -- 	ODBC_APP_DEFINES=
> -- 	ODBC_APP_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_APP_COMPILER_FLAGS=
> -- 	ODBC_APP_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbc
> -- 	ODBC_DRIVER_DEFINES=
> -- 	ODBC_DRIVER_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_DRIVER_COMPILER_FLAGS=
> -- 	ODBC_DRIVER_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbcinst
> -- Found the following ICU libraries:
> --   uc (required)
> CMake Error at contrib/ssl/CMakeLists.txt:5 (include):
>   include could not find load file:
> 
>     cmake/prevent_in_source_builds.cmake
> 
> 
> -- CMAKE_BUILD_TYPE: RelWithDebInfo
> CMake Error at contrib/ssl/CMakeLists.txt:119 (include):
>   include could not find load file:
> 
>     cmake/arch.cmake
> 
> 
> CMake Error at contrib/ssl/CMakeLists.txt:120 (include):
>   include could not find load file:
> 
>     cmake/sanitize.cmake
> 
> 
> CMake Error at cmake/Modules/FindiODBC.cmake:30 (include):
>   include could not find load file:
> 
>     cmake/extract_flags.cmake
> Call Stack (most recent call first):
>   cmake/Modules/FindODBC.cmake:121 (find_package)
>   contrib/ssl/CMakeLists.txt:123 (find_package)
> 
> 
> CMake Error at cmake/Modules/FindiODBC.cmake:35 (message):
>   ODBC iODBC: Only one of ODBC_IODBC_DIR and ODBC_IODBC_CONFIG_SCRIPT can be
>   specified at the same time.
> Call Stack (most recent call first):
>   cmake/Modules/FindODBC.cmake:121 (find_package)
>   contrib/ssl/CMakeLists.txt:123 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/miraj/Downloads/clickhouse-odbc/build/CMakeFiles/CMakeOutput.log".

Thereafter, getting that `ODBC iODBC: Only one of ODBC_IODBC_DIR=/usr/local/Cellar/libiodbc/3.52.13  and ODBC_IODBC_CONFIG_SCRIPT=/usr/local/bin/iodbc-config can be specified  at the same time.`. So, i explicitly set one (tried with indeed setting one by one both) of the variables to FALSE in `cmake/Modules/FindiODBC.cmake`

> (base) miraj@Miraj-13inch-mac build % cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl -DICU_ROOT=$(brew --prefix)/opt/icu4c ..
> -- CMAKE_BUILD_TYPE: RelWithDebInfo
> -- Using ODBC: iODBC
> -- 	ODBC_DIR=/usr/local/Cellar/libiodbc/3.52.13
> -- 	ODBC_CONFIG_SCRIPT=/usr/local/bin/iodbc-config
> -- 	ODBC_IODBC_IODBCTEST=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctest
> -- 	ODBC_IODBC_IODBCTESTW=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctestw
> -- 	ODBC_APP_DEFINES=
> -- 	ODBC_APP_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_APP_COMPILER_FLAGS=
> -- 	ODBC_APP_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbc
> -- 	ODBC_DRIVER_DEFINES=
> -- 	ODBC_DRIVER_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_DRIVER_COMPILER_FLAGS=
> -- 	ODBC_DRIVER_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbcinst
> -- Found the following ICU libraries:
> --   uc (required)
> -- CMAKE_BUILD_TYPE: RelWithDebInfo
> CMake Error at cmake/Modules/FindiODBC.cmake:35 (message):
>   ODBC iODBC: Only one of ODBC_IODBC_DIR=/usr/local/Cellar/libiodbc/3.52.13
>   and ODBC_IODBC_CONFIG_SCRIPT=/usr/local/bin/iodbc-config can be specified
>   at the same time.
> Call Stack (most recent call first):
>   cmake/Modules/FindODBC.cmake:121 (find_package)
>   contrib/ssl/CMakeLists.txt:123 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/miraj/Downloads/clickhouse-odbc/build/CMakeFiles/CMakeOutput.log".

**But now i am stuck, with this error, any help would be great:** . `CMake Error at cmake/Modules/FindODBC.cmake:199 (add_library): add_library cannot create imported target "ODBC::App" because another target with the same name already exists.`

> (base) miraj@Miraj-13inch-mac build % cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl -DICU_ROOT=$(brew --prefix)/opt/icu4c ..
> -- CMAKE_BUILD_TYPE: RelWithDebInfo
> -- Using ODBC: iODBC
> -- 	ODBC_DIR=/usr/local/Cellar/libiodbc/3.52.13
> -- 	ODBC_CONFIG_SCRIPT=/usr/local/bin/iodbc-config
> -- 	ODBC_IODBC_IODBCTEST=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctest
> -- 	ODBC_IODBC_IODBCTESTW=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctestw
> -- 	ODBC_APP_DEFINES=
> -- 	ODBC_APP_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_APP_COMPILER_FLAGS=
> -- 	ODBC_APP_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbc
> -- 	ODBC_DRIVER_DEFINES=
> -- 	ODBC_DRIVER_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_DRIVER_COMPILER_FLAGS=
> -- 	ODBC_DRIVER_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbcinst
> -- Found the following ICU libraries:
> --   uc (required)
> -- CMAKE_BUILD_TYPE: RelWithDebInfo
> -- Using ODBC: iODBC
> -- 	ODBC_DIR=/usr/local/Cellar/libiodbc/3.52.13
> -- 	ODBC_CONFIG_SCRIPT=/usr/local/bin/iodbc-config
> -- 	ODBC_IODBC_IODBCTEST=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctest
> -- 	ODBC_IODBC_IODBCTESTW=/usr/local/Cellar/libiodbc/3.52.13/bin/iodbctestw
> -- 	ODBC_APP_DEFINES=
> -- 	ODBC_APP_INCLUDE_DIRS=/usr/local/Cellar/libiodbc/3.52.13/include
> -- 	ODBC_APP_COMPILER_FLAGS=
> -- 	ODBC_APP_LINKER_FLAGS=-L/usr/local/Cellar/libiodbc/3.52.13/lib;-liodbc
> CMake Error at cmake/Modules/FindODBC.cmake:199 (add_library):
>   add_library cannot create imported target "ODBC::App" because another
>   target with the same name already exists.
> Call Stack (most recent call first):
>   contrib/ssl/CMakeLists.txt:123 (find_package)
> 
> 
> CMake Error at cmake/Modules/FindODBC.cmake:203 (target_link_libraries):
>   Cannot specify link libraries for target "ODBC::App" which is not built by
>   this project.
> Call Stack (most recent call first):
>   contrib/ssl/CMakeLists.txt:123 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/miraj/Downloads/clickhouse-odbc/build/CMakeFiles/CMakeOutput.log".

**odbc.ini File**

> Insert the content of this file into ~/.odbc.ini or /etc/odbc.ini files.
> 
> [ODBC Data Sources]
> ClickHouse DSN (ANSI)    = ClickHouse ODBC Driver (ANSI)
> ClickHouse DSN (Unicode) = ClickHouse ODBC Driver (Unicode)
> 
> [ClickHouse DSN (ANSI)]
> Driver      = ClickHouse ODBC Driver (ANSI)
> Description = DSN (localhost) for ClickHouse ODBC Driver (ANSI)
> 
> New all-in one way to specify connection with [optional] settings:
>  Url = https://default:password@localhost:8443/query?database=default&max_result_bytes=4000000&buffer_size=3000000
> 
> ...or minimal (will connect to port 8443 if protocol is "https://" or 8123 if it is "http://"):
> Url = https://localhost
> 
> Old way:
> Server = 192.168.192.212
> Database = default
> Port = 8123
> Proto = http
> 
> 
> [ClickHouse DSN (Unicode)]
> Driver      = ClickHouse ODBC Driver (Unicode)
> Description = DSN (localhost) for ClickHouse ODBC Driver (Unicode)

**odbcinst.ini File**

> [ODBC Drivers]
> PostgreSQL Unicode              = Installed
> Cloudera ODBC Driver for Impala = Installed
> ClickHouse ODBC Driver (ANSI)    = Installed
> ClickHouse ODBC Driver (Unicode) = Installed
> 
> [PostgreSQL Unicode]
> Description = PostgreSQL ODBC driver
> Driver      = /usr/local/lib/psqlodbcw.so
> 
> [Cloudera ODBC Driver for Impala]
> Driver = /opt/cloudera/impalaodbc/lib/universal/libclouderaimpalaodbc.dylib
> 
> [ClickHouse ODBC Driver (ANSI)]
> Description = ODBC Driver (ANSI) for ClickHouse
> Driver      = /usr/local/lib64/libclickhouseodbc.so
> Setup       = /usr/local/lib64/libclickhouseodbc.so
> UsageCount  = 1
> 
> [ClickHouse ODBC Driver (Unicode)]
> Description = ODBC Driver (Unicode) for ClickHouse
> Driver      = /usr/local/lib64/libclickhouseodbcw.so
> Setup       = /usr/local/lib64/libclickhouseodbcw.so
> UsageCount  = 1

**Comment by traceon** [comment]
Try removing the entire source tree, and cloning afresh with this command:
```sh
git clone --recursive git@github.com:ClickHouse/clickhouse-odbc.git
```

**Comment by mirajgodha** [comment]
Thanks @traceon .. --recursive cloning worked. I can connect to clickhouse from Tableau using ODBC datasource now.
