### ISSUE TITLE
trying to connect clickhouse to tableau but unable to connect

### ISSUE THREAD

**Issue by 23-Deepti** [ClickHouse/clickhouse-odbc#346]
I am trying to connect clickhouse to tableau and followed this blog "https://altinity.com/blog/2018/7/19/tableau-with-clickhouse" but when I connect DSN, the processing request time take too long. I waited for 2hrs to finish processing request but still no success. can anybody tell me why this is happeing?

**Comment by traceon** [comment]
Try trivial queries like `SELECT 1`? Do they work?

**Comment by 23-Deepti** [comment]
It does not work Even if I search for any table present in clickhouse
database on Tableau it shows no matches found.

**Comment by 23-Deepti** [comment]
I published the same question on stackoverflow with screenshots and some
detail, you can check this link '
https://stackoverflow.com/questions/66316706/how-to-connect-clickhouse-to-tableau-desktop-on-windows
'

Thanks

**Comment by alexander-chashnikov** [comment]
You just need to choose your created DSN - `clickhouse_demo`.
Don't use the default DNS which was created after the ODBC driver installation `ClickHouse DSN (Unicode)` and `ClickHouse DSN (ANSI)` if you didn't configure it.

**Comment by 23-Deepti** [comment]
Thanks. Problem solved
