### ISSUE TITLE
no build clickhouse-odbc-bridge aarch64

### ISSUE THREAD

**Issue by roygbip** [ClickHouse/clickhouse-odbc#350]
There is no build clickhouse-odbc-bridge for aarch64 in ci.

How do I build it myself ?

```shell
./packager --output-dir=$HOME/clickhouse --package-type binary --compiler=clang-11-aarch64  --version=21.1.2.15  --official
```
this is no clickhouse-odbc-bridge output.

**Comment by traceon** [comment]
You should ask this question in the main ClickHouse project: https://github.com/ClickHouse/ClickHouse
`clickhouse-odbc-bridge` is a part of the ClickHouse server, not ClickHouse ODBC driver project.

**Comment by roygbip** [comment]
ok
