### ISSUE TITLE
error when try cmake --build . --config RelWithDebInfo on MAC OS BIG SUR 11.3.1    

### ISSUE THREAD

**Issue by dimaaasex91** [ClickHouse/clickhouse-odbc#355]
[ 16%] Built target Foundation
[ 65%] Built target crypto
[ 68%] Built target ssl
[ 70%] Built target Crypto
[ 76%] Built target XML
[ 78%] Built target JSON
[ 81%] Built target Util
[ 90%] Built target Net
[ 91%] Built target NetSSL
[ 93%] Built target clickhouse-odbc-impl
[ 95%] Built target clickhouse-odbcw-impl
[ 95%] Built target clickhouse-odbcw
[ 95%] Built target clickhouse-odbc
[ 95%] Built target clickhouse-odbc-load-ut
Consolidate compiler generated dependencies of target nanodbc
[ 95%] Building CXX object contrib/nanodbc/CMakeFiles/nanodbc.dir/nanodbc/nanodbc.cpp.o
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:79:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/cstddef:37:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:79:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
      ~~^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:501:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/type_traits:418:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:502:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/typeinfo:60:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/exception:83:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:671:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/new:93:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:672:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/utility:205:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:673:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/limits:121:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:674:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iterator:423:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:674:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iterator:562:13: error: unknown type name 'ptrdiff_t'
    typedef ptrdiff_t difference_type;
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iterator:623:56: error: unknown type name 'ptrdiff_t'
template<class _Category, class _Tp, class _Distance = ptrdiff_t,
                                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iterator:989:66: error: unknown type name 'ptrdiff_t'
          class _Traits = char_traits<_CharT>, class _Distance = ptrdiff_t>
                                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iterator:989:54: error: template parameter missing a default argument
          class _Traits = char_traits<_CharT>, class _Distance = ptrdiff_t>
                                                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iterator:989:27: note: previous default template argument defined here
          class _Traits = char_traits<_CharT>, class _Distance = ptrdiff_t>
                          ^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:677:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/tuple:154:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:681:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/atomic:576:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/__threading_support:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/chrono:831:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:681:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/atomic:581:
/Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/version:1:1: error: expected unqualified-id
2.13.0
^
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.cpp:16:
In file included from /Users/yurchyshynd/Desktop/odbc/clickhouse-odbc/contrib/nanodbc/nanodbc/nanodbc.h:80:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/functional:504:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/memory:681:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/atomic:1052:73: error: unknown type name 'ptrdiff_t'
_Tp* __cxx_atomic_fetch_add(__cxx_atomic_base_impl<_Tp*> volatile* __a, ptrdiff_t __delta, memory_order __order) _NOEXCEPT {
                                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/atomic:1057:65: error: unknown type name 'ptrdiff_t'
_Tp* __cxx_atomic_fetch_add(__cxx_atomic_base_impl<_Tp*> * __a, ptrdiff_t __delta, memory_order __order) _NOEXCEPT {
                                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/atomic:1073:73: error: unknown type name 'ptrdiff_t'
_Tp* __cxx_atomic_fetch_sub(__cxx_atomic_base_impl<_Tp*> volatile* __a, ptrdiff_t __delta, memory_order __order) _NOEXCEPT {
                                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/atomic:1078:65: error: unknown type name 'ptrdiff_t'
_Tp* __cxx_atomic_fetch_sub(__cxx_atomic_base_impl<_Tp*> * __a, ptrdiff_t __delta, memory_order __order) _NOEXCEPT {
                                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
gmake[2]: *** [contrib/nanodbc/CMakeFiles/nanodbc.dir/build.make:76: contrib/nanodbc/CMakeFiles/nanodbc.dir/nanodbc/nanodbc.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2119: contrib/nanodbc/CMakeFiles/nanodbc.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2

**Comment by evmnaumov** [comment]
Have the same trouble. On Catalina works well!

**Comment by traceon** [comment]
Try this:

1. Install/update [Xcode](https://apps.apple.com/am/app/xcode/id497799835?mt=12) from App Store.
2. Open it at least once to accept the end-user license agreement and automatically install the required components.
3. Make sure that the latest Command Line Tools are installed and selected in the system:
    ```sh
    sudo rm -rf /Library/Developer/CommandLineTools
    sudo xcode-select --install
    ```
4. Update `brew` and install dependencies (assuming you need iODBC version of the driver):
   ```sh
   brew update
   brew install git cmake make poco openssl icu4c libiodbc
   ```
5. Clone the repo recursively and build afresh:
   ```sh
   rm -rf clickhouse-odbc
   git clone --recursive https://github.com/ClickHouse/clickhouse-odbc.git

   cd clickhouse-odbc
   mkdir build
   cd build

   cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl -DICU_ROOT=$(brew --prefix)/opt/icu4c ..
   cmake --build . --config RelWithDebInfo
   cmake --build . --config RelWithDebInfo --target package
   ```

**Comment by dimaaasex91** [comment]
I followed all these steps but it didn't work for me. the error is the same

**Comment by dimaaasex91** [comment]
> Try this:
> 
> 1. Install/update [Xcode](https://apps.apple.com/am/app/xcode/id497799835?mt=12) from App Store.
> 2. Open it at least once to accept the end-user license agreement and automatically install the required components.
> 3. Make sure that the latest Command Line Tools are installed and selected in the system:
>    ```shell
>    sudo rm -rf /Library/Developer/CommandLineTools
>    sudo xcode-select --install
>    ```
> 4. Update `brew` and install dependencies (assuming you need iODBC version of the driver):
>    ```shell
>    brew update
>    brew install git cmake make poco openssl icu4c libiodbc
>    ```
> 5. Clone the repo recursively and build afresh:
>    ```shell
>    rm -rf clickhouse-odbc
>    git clone --recursive https://github.com/ClickHouse/clickhouse-odbc.git
>    
>    cd clickhouse-odbc
>    mkdir build
>    cd build
>    
>    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl -DICU_ROOT=$(brew --prefix)/opt/icu4c ..
>    cmake --build . --config RelWithDebInfo
>    cmake --build . --config RelWithDebInfo --target package
>    ```
I followed all these steps but it didn't work for me. the error is the same

**Comment by traceon** [comment]
I was able to reproduce the problem, and will work on the fix.

Meanwhile, as a quick workaround, you can specify `-DBUILD_TESTING=OFF` during CMake "configure" step (assuming, you are not interested in building the test executables.)

**Comment by evmnaumov** [comment]
> I was able to reproduce the problem, and will work on the fix.
> 
> Meanwhile, as a quick workaround, you can specify `-DBUILD_TESTING=OFF` during CMake "configure" step (assuming, you are not interested in building the test executables.)

Great! It works! Thank you, my savior!

**Comment by dimaaasex91** [comment]
> e the problem, and will work on the fix.
> 
> Meanwhile, as a quick workaround, you can specify `-DBUILD_TESTING=OFF` during CMake "configure" step (assuming, you are not interested in building the test executables.)

Thanks it works

**Comment by tarunparmar** [comment]
> Try this:
> 
> 1. Install/update [Xcode](https://apps.apple.com/am/app/xcode/id497799835?mt=12) from App Store.
> 2. Open it at least once to accept the end-user license agreement and automatically install the required components.
> 3. Make sure that the latest Command Line Tools are installed and selected in the system:
>    ```shell
>    sudo rm -rf /Library/Developer/CommandLineTools
>    sudo xcode-select --install
>    ```
> 4. Update `brew` and install dependencies (assuming you need iODBC version of the driver):
>    ```shell
>    brew update
>    brew install git cmake make poco openssl icu4c libiodbc
>    ```
> 5. Clone the repo recursively and build afresh:
>    ```shell
>    rm -rf clickhouse-odbc
>    git clone --recursive https://github.com/ClickHouse/clickhouse-odbc.git
>    
>    cd clickhouse-odbc
>    mkdir build
>    cd build
>    
>    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENSSL_ROOT_DIR=$(brew --prefix)/opt/openssl -DICU_ROOT=$(brew --prefix)/opt/icu4c ..
>    cmake --build . --config RelWithDebInfo
>    cmake --build . --config RelWithDebInfo --target package
>    ```

redoing step 4 onwards seems to have worked

but the issue now is how to link the driver with ODBC manager (on mac os), tried to add file and it asked for password upon which it seems its doing something but does not actually show the driver in list.
