### ISSUE TITLE
CentOS 8 Installation issue

### ISSUE THREAD

**Issue by johnhummelAltinity** [ClickHouse/clickhouse-odbc#360]
When installing the packaged 1.1.9 version of the RPM on CentOS 8, the following error is displayed:

```bash
error: Failed dependencies:
   libicuuc.so.50()(64bit) is needed by clickhouse-odbc-1.1.9-1.el7.x86_64
```

I'll attempt to build from source code, but it appears that the current `libicu` version used in CentOS 8 and above doesn't have the necessary libraries for clickhouse-odbc version 1.1.9.

**Comment by traceon** [comment]
Yes, the binary is compiled under CentOS 7. You need to recompile for your system.

**Comment by johnhummelAltinity** [comment]
@traceon I think the main issue
