### ISSUE TITLE
data type datetime64 shows up as a string in Tableau (using Clikchouse ODBC driver and connector)

### ISSUE THREAD

**Issue by jorgecabrera85** [ClickHouse/clickhouse-odbc#364]
![image](https://user-images.githubusercontent.com/86806156/124194558-caf5fb80-da96-11eb-93d6-83608b69263e.png)

**Comment by traceon** [comment]
Are you using https://github.com/Altinity/clickhouse-tableau-connector-odbc ?

**Comment by jorgecabrera85** [comment]
> Are you using https://github.com/Altinity/clickhouse-tableau-connector-odbc ?

yes. as shown in the picture, it says "Connector Class:clickhouse_odbc. Version: 0.0.1"
