### ISSUE TITLE
When will your new release be accessed to download? Cant build from sources :( Too many errors <неразрешенный внешний символ>

### ISSUE THREAD

**Issue by theSaintBelial** [ClickHouse/clickhouse-odbc#372]

**Comment by traceon** [comment]
Please post the build log. Currently, `master` compiles without problem on all target platforms: https://github.com/ClickHouse/clickhouse-odbc/actions

**Comment by theSaintBelial** [comment]
> Please post the build log. Currently, `master` compiles without problem on all target platforms: https://github.com/ClickHouse/clickhouse-odbc/actions

When I wrote about errros, I didnt consider it's your fault :) Im just immature in building c++ projects

Errors when I'm trying to execute this command:

`cmake --build . --config RelWithDebInfo --target package`

Many errors like this:

`PocoNetmd.lib(SocketImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_recvfrom. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
PocoNetmd.lib(SocketImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_send. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
PocoNetmd.lib(SocketImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_sendto. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
PocoNetmd.lib(SocketImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_setsockopt. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
PocoNetmd.lib(SocketImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_shutdown. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
PocoNetmd.lib(SocketImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_socket. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
PocoNetmd.lib(SocketImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_WSAPoll. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
PocoNetmd.lib(IPAddressImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_inet_addr. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
PocoNetmd.lib(IPAddressImpl.obj) : error LNK2001: неразрешенный внешний символ __imp_ntohl. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-ut.vcxproj]
C:\Users\xfear\clickhouse-odbc\build\driver\test\RelWithDebInfo\clickhouse-odbcw-ut.exe : fatal error LNK1120: неразрешенных внешних элементов: 33 [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-
ut.vcxproj]`

`nanodbcmd.lib(nanodbc.obj) : error LNK2001: неразрешенный внешний символ SQLAllocHandle. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-nano-it.vcxproj]
nanodbcmd.lib(nanodbc.obj) : error LNK2001: неразрешенный внешний символ SQLBindCol. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-nano-it.vcxproj]
nanodbcmd.lib(nanodbc.obj) : error LNK2001: неразрешенный внешний символ SQLCancel. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-nano-it.vcxproj]
nanodbcmd.lib(nanodbc.obj) : error LNK2001: неразрешенный внешний символ SQLColAttribute. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-nano-it.vcxproj]
nanodbcmd.lib(nanodbc.obj) : error LNK2001: неразрешенный внешний символ SQLColumns. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-nano-it.vcxproj]
nanodbcmd.lib(nanodbc.obj) : error LNK2001: неразрешенный внешний символ SQLCompleteAsync. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-nano-it.vcxproj]
nanodbcmd.lib(nanodbc.obj) : error LNK2001: неразрешенный внешний символ SQLConnect. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-nano-it.vcxproj]`

`misc_it.obj : error LNK2001: неразрешенный внешний символ SQLGetDiagRecW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLConnectW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLFreeHandle. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLSetStmtAttrW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLAllocHandle. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLFetch. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLSetEnvAttr. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLColAttributeW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLExecute. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLPrepareW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLDescribeColW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLExecDirectW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLGetData. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLDisconnect. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLGetStmtAttrW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
misc_it.obj : error LNK2001: неразрешенный внешний символ SQLDriverConnectW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
column_bindings_it.obj : error LNK2001: неразрешенный внешний символ SQLBindCol. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
statement_parameter_bindings_it.obj : error LNK2001: неразрешенный внешний символ SQLSetDescFieldW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
statement_parameter_bindings_it.obj : error LNK2001: неразрешенный внешний символ SQLMoreResults. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
statement_parameter_bindings_it.obj : error LNK2001: неразрешенный внешний символ SQLBindParameter. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
performance_it.obj : error LNK2001: неразрешенный внешний символ SQLGetConnectAttrW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
performance_it.obj : error LNK2001: неразрешенный внешний символ SQLSetConnectAttrW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
performance_it.obj : error LNK2001: неразрешенный внешний символ SQLNumResultCols. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
performance_it.obj : error LNK2001: неразрешенный внешний символ SQLStatisticsW. [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse-odbcw-client-it.vcxproj]
C:\Users\xfear\clickhouse-odbc\build\driver\test\RelWithDebInfo\clickhouse-odbcw-client-it.exe : fatal error LNK1120: неразрешенных внешних элементов: 24 [C:\Users\xfear\clickhouse-odbc\build\driver\test\clickhouse
-odbcw-client-it.vcxproj]`

**Comment by traceon** [comment]
Please also post the output of the entire cmake configuration command.

**Comment by theSaintBelial** [comment]
I dont really catch what u mean, but I hope u talk about this one:

`cmake -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`

**Comment by theSaintBelial** [comment]
> Please also post the output of the entire (fresh) cmake configuration command.

U mean this one?

`cmake -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`
Logs:

`C:\Users\xfear\clickhouse-odbc\build>cmake -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- Using ODBC: MDAC
--      ODBC_APP_DEFINES=
--      ODBC_APP_INCLUDE_DIRS=C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/um
--      ODBC_APP_COMPILER_FLAGS=
--      ODBC_APP_LINKER_FLAGS=C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x86/odbc32.lib
--      ODBC_DRIVER_DEFINES=
--      ODBC_DRIVER_INCLUDE_DIRS=C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/um
--      ODBC_DRIVER_COMPILER_FLAGS=
--      ODBC_DRIVER_LINKER_FLAGS=C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x86/odbccp32.lib;C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x86/WS2_32.Lib;C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/lib/x86/legacy_stdio_definitions.lib
-- Found ODBC: TRUE
-- Poco package version: 1.9.4
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Checking for C++14 compiler
-- Checking for C++14 compiler - available
-- Found message compiler: C:/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x86/mc.exe
-- Building static libraries
-- Building without tests & samples
-- Using internal sqlite, zlib, pcre, expat, ...
-- Couldn't find MySQL or MariaDB
-- MySQL Support Disabled - no MySQL library
-- Found ODBC: C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/um
-- Windows native ODBC Support Enabled
-- CMake 3.21.1 successfully configured Poco using Visual Studio 16 2019 generator
-- Installation target path: C:/Program Files/clickhouse-odbc
-- C_FLAGS:  =/DWIN32 /D_WINDOWS /W3
-- CMAKE_C_FLAGS_DEBUG:=/MDd /Zi /Ob0 /Od /RTC1 -DBUILD_TYPE_DEBUG
-- CMAKE_C_FLAGS_RELEASE:=/MD /O2 /Ob2 /DNDEBUG -DNDEBUG -DBUILD_TYPE_RELEASE
-- CMAKE_C_FLAGS_MINSIZEREL:=/MD /O1 /Ob1 /DNDEBUG -DNDEBUG -DBUILD_TYPE_MINSIZEREL
-- CMAKE_C_FLAGS_RELWITHDEBINFO:=/MD /Zi /O2 /Ob1 /DNDEBUG -DNDEBUG -DBUILD_TYPE_RELWITHDEBINFO
--
--
-- CXX_FLAGS:=/DWIN32 /D_WINDOWS /W3 /GR /EHsc /Zc:__cplusplus
-- CMAKE_CXX_FLAGS_DEBUG:=/MDd /Zi /Ob0 /Od /RTC1 -DBUILD_TYPE_DEBUG
-- CMAKE_CXX_FLAGS_RELEASE:=/MD /O2 /Ob2 /DNDEBUG -DNDEBUG -DBUILD_TYPE_RELEASE
-- CMAKE_CXX_FLAGS_MINSIZEREL:=/MD /O1 /Ob1 /DNDEBUG -DNDEBUG -DBUILD_TYPE_MINSIZEREL
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO:=/MD /Zi /O2 /Ob1 /DNDEBUG -DNDEBUG -DBUILD_TYPE_RELWITHDEBINFO
-- Building: Encodings
-- Building: XML
-- Building: JSON
-- Building: Util
-- Building: Net
-- Building: MongoDB
-- Building: Redis
-- Building: NetSSL_Win
-- Building: NetSSL_OpenSSL
-- Building: Crypto
-- Building: Data
-- Building: Zip
-- Building: PageCompiler
-- Building: File2Page
-- nanodbc version: 2.13.0
-- nanodbc compile: C++14
-- nanodbc feature: ODBC Version Override - OFF
-- nanodbc feature: Disable async features - OFF
-- nanodbc feature: Enable Unicode - 0
-- nanodbc feature: Enable Boost - OFF
-- nanodbc feature: Enable SQL_NO_DATA bug workaround - OFF
-- nanodbc build: Enable nanodbc target - STATIC
-- nanodbc build: Disable install target - 1
-- nanodbc build: Disable tests target - 1
-- nanodbc build: Disable examples target - 1
-- clickhouse-odbc: ANSI
-- clickhouse-odbcw: Unicode
-- Testing with:
        TEST_DSN_LIST=ClickHouse DSN (ANSI);ClickHouse DSN (Unicode)
        PERL=PERL-NOTFOUND
        PERL_USES_MDAC=0
        PERL_USES_UNIXODBC=0
        PERL_USES_IODBC=0
        PYTHON2=PYTHON2-NOTFOUND
        PYTHON2_USES_MDAC=0
        PYTHON2_USES_UNIXODBC=0
        PYTHON2_USES_IODBC=0
        PYTHON3=PYTHON3-NOTFOUND
        PYTHON3_USES_MDAC=0
        PYTHON3_USES_UNIXODBC=0
        PYTHON3_USES_IODBC=0
        ODBC_UNIXODBC_ISQL=
        ODBC_UNIXODBC_IUSQL=
        ODBC_IODBC_IODBCTEST=
        ODBC_IODBC_IODBCTESTW=
        SQLCMD=SQLCMD-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/xfear/clickhouse-odbc/build
`

**Comment by theSaintBelial** [comment]
> Please also post the output of the entire (fresh) cmake configuration command.

As I consider the problems sql.dll libraries not found is that builder cannot found MySQL Library at all. I installed MySQL Developer Kit and nothing has happened. Havent found any instructions about MySQL in your installation quide :(

**Comment by theSaintBelial** [comment]
Omg....ok, I just used Developer CMD instead of x64 Native Tools...
