### ISSUE TITLE
Unicode driver fails on Win10 with Yandex Playground

### ISSUE THREAD

**Issue by dima-altinity** [ClickHouse/clickhouse-odbc#380]
Hi

 I tried to connect to Yandex Playground (https://play-api.clickhouse.com:8443) using latest driver. Ansi driver works fine.
 Unicode driver generates error if you try to SELECT from any table.
 ODBC trace log attached.

[SQL.LOG.zip](https://github.com/ClickHouse/clickhouse-odbc/files/7465644/SQL.LOG.zip)

Thanks
Dima

**Comment by alexey-milovidov** [comment]
Yandex Playground is deprecated for years already.
