### ISSUE TITLE
"Sets" seems not to be recognized with this last connector version

### ISSUE THREAD

**Issue by Fred5778** [ClickHouse/clickhouse-odbc#387]
Hi,

I have tried your new connector with the hope it would correct limitations because Tableau does not understand the ClickHouse SQL dialect.
Before I had a several limitations and issues with JOIN ON syntax and LOD expressions as FIXED, INCLUDE etc.

for example :
Une erreur s'est produite lors de la communication avec la source de données Autres bases de données (ODBC) 'qoe_fixe'
Problème de connexion : Tableau n'a pas pu se connecter à la source de données.
Code d'erreur : B19090E0
HTTP status code: 501
Received error:
Code: 48, e.displayText() = DB::Exception: JOIN ON does not support OR. Unexpected '(zipcode = t0.zipcode) OR (isNull(zipcode) AND isNull(t0.zipcode))': While processing (zipcode = t0.zipcode) OR (isNull(zipcode) AND isNull(t0.zipcode)) (version 21.3.15.4 (official build))

but there were no errors displayed on calculated fields, even if they were based on "sets" etc..

_Now, If I used your new connector, I encounter another problem:_
**It seems that "sets" are not recognised??**
For exemple :
In this calculated field I use a set called  « Dsl_Indispo_One_Day »

SUM(IIF(CONTAINS([Infra],'o1'),IIF([Dsl_Indispo_One_Day], 1, 0),0)) / SUM(IIF(CONTAINS([Infra],'o1'),1,0))
![image](https://user-images.githubusercontent.com/21174740/149119656-84b4e7f9-85ab-4d70-b298-b98a74a770fa.png)

With the new connector, you can see that it has been replaced by [test] (Why ?) and it is writen that le calculation contains errors.
![image](https://user-images.githubusercontent.com/21174740/149119759-05dc592a-91f8-4128-b42b-9bc90e4bf7d0.png)

If I change in the [test] in _%NbIndispoDsl to use a condition instead of the « set », namely :
 
![image](https://user-images.githubusercontent.com/21174740/149120525-3747955e-8933-49dd-b4c8-ebda470048a0.png)

Instead of 
 
![image](https://user-images.githubusercontent.com/21174740/149120543-888242ac-c911-42a5-82e8-ae05e37bdce8.png)

The error disappears.

But, it doesn’t work with an other field.
![image](https://user-images.githubusercontent.com/21174740/149120582-b4f0108c-753f-498b-9bc8-dd67bb71856a.png)

If I do the same, it leads to an invalid calculation

and my dashboards are not displayed...

Thanks for your help.

Fred

**Comment by traceon** [comment]
https://github.com/Altinity/clickhouse-tableau-connector-odbc/issues/19 is the right place to track this issue.
