### ISSUE TITLE
How to build 32-bit clickhouse-odbc on centos7 ?

### ISSUE THREAD

**Issue by FanWuu** [ClickHouse/clickhouse-odbc#393]
How to build 32-bit clickhouse-odbc on centos7 ?

**Comment by traceon** [comment]
Have you tried following the [instructions](https://github.com/ClickHouse/clickhouse-odbc#building-from-sources)?
You will need a compiler that can target x86 (32-bit) with the corresponding runtime, and that satisfied requirements from the link above.
