### ISSUE TITLE
Data parsing issue using odbc driver in Tableau Desktop

### ISSUE THREAD

**Issue by tarunparmar** [ClickHouse/clickhouse-odbc#395]
I build the driver using source on my company mac and was able to connect to Clickhouse after registering the driver with ODBC manager , then I used custom sql to extract data and noticed that some columns dont parse correct. 
The data look normal in dbeaver (SQL application/developer).

I tested both 1.1.9 and 1.1.10 release to see same outcome.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/17690950/169523488-e6c0e5f1-c68d-4c53-a1a5-a9cff145e8c9.png">

**Comment by Enmk** [comment]
Hi @tarunparmar ! What is the encoding of the data in clickhouse? What results do you get when you select via `clickhouse client`?
