### ISSUE TITLE
Could not find ODBCINSTGetProperties() from 

### ISSUE THREAD

**Issue by belonesox** [ClickHouse/clickhouse-odbc#396]
I has compile driver from commit 860b06f934d850e9db711f4922600c41d2a9498c

/etc/odbcinst.ini
```
[ClickhouseU]
Description     = ODBC for ClickhouseU
Driver          = /usr/local/lib64/libclickhouseodbcw.so
Setup       = /usr/local/lib64/libclickhouseodbcw.so
UsageCount  = 1
```

I was using unixODBC project to test ODBC connection to CH.
( «unixODBC-gui-qt» fedora package, «ODBCCreateDataSourceQ5» application).

I got 

«Could not find ODBCINSTGetProperties()»

«Could not construct a property list for (ClickhouseU). Contact your; SysAdmin, driver vendor, or folks at the unixODBC project for support.»

![image](https://user-images.githubusercontent.com/1609739/170234838-9f9888a7-1222-45f6-b37b-b61540ffc9a2.png)

I am doing something wrong?
Should it work?

**Comment by Enmk** [comment]
This looks like some extension method required by that particular tool only. As of now, clickhouse-odbc doesn't export that method (`ODBCINSTGetProperties`); hence, this GUI-tool is not supported.
However, you can take a look at how to properly set up all configuration files in CI/CD workflows:
https://github.com/ClickHouse/clickhouse-odbc/blob/a623c895eb9754f7231d91bc8b09d31fae9e8cee/.github/workflows/Linux.yml#L156-L210

Alternatively, you can submit a PR that implements that particular method.
