### ISSUE TITLE
Не создаётся Extract connection 

### ISSUE THREAD

**Issue by Fliner042** [ClickHouse/clickhouse-odbc#411]
После публикации Data Sources не создаётся extract

Выдаёт ошибку: 
check the data connection page for necessary updates to an access token or embedded credentials

проверили, что DSN совпадает и на сервере, и на десктопе

Так же бывает, что созданный extract не обновляет и в Resolution Details также выдаёт ошибку: 
check the data connection page for necessary updates to an access token or embedded credential

Также при подключении в десктопной версии, периодически возникают warnings:
Tableau was unable to generate a query to perform this operation.
Generic ODBC requires additional configuration. The driver and DSN (data source name) must be installed and configured to match the connection.
Unable to connect using the DSN named "ClickHouse". Check that the DSN exists and is a valid connection.

**Comment by Enmk** [comment]
Hi @Fliner042, thank you for submitting!

Could you please specify host OS and versions of the software involved (clickhouse-odbc, ODBC driver, Tableu).

Also, were you able to connect Tableau to CH via [clickhouse-jdbc](https://clickhouse.com/learn/lessons/connect-tableau-to-clickhouse/) ?

**Comment by Fliner042** [comment]
Hi @Enmk!
Host OS - Ubuntu 18
clickhouse-odbc - 1.1.10.20210822 (last release)
ODBC driver - ClickHouse ODBC Driver (Unicode)
Tableau -  2021.3 desktop version

No, I haven't tried connecting, and in Path: "C:\Program Files\Tableau\Drivers" driver only postgre...
I'll try to install clickhouse-jdbc

**Comment by Enmk** [comment]
> Host OS - Ubuntu 18
> in Path: "C:\Program Files\Tableau\Drivers" driver only postgre...
How? I mean it looks like something is messed up, on Linuxes (like Ubuntu) there could be no path like `c:\yada-yada`. So either you are on Windows or your path is set incorrectly.

Also, taking a look at 
- https://github.com/ClickHouse/clickhouse-odbc/blob/master/.github/workflows/Linux.yml (for linux machine)

Might give you an idea on how to set up driver and driver manager.

Or you might find README useful: 
- https://github.com/ClickHouse/clickhouse-odbc#configuration-mdacwdac-microsoftwindows-data-access-components
- https://github.com/ClickHouse/clickhouse-odbc#configuration-unixodbc

**Comment by dima-altinity** [comment]
@Fliner042 

I highly recommend you to switch to use Altinity Tableau Connector for ClickHouse
Check details here:
https://github.com/Altinity/tableau-connector-for-clickhouse/

JDBC version is recommended. But if you are 100% on Windows you could still try to use ODBC version and install it directly from Gallery
https://exchange.tableau.com/products/604

**Comment by Fliner042** [comment]
@Enmk thanks!)
But I mean in my local desctop version
And I have some trouble:

Tableau was unable to generate a query to perform this operation.
Generic ODBC requires additional configuration. The driver and DSN (data source name) must be installed and configured to match the connection.
Unable to connect using the DSN named "ClickHouse". Check that the DSN exists and is a valid connection.

On server we have ubuntu

And connection in server named "ClickHouse" and in my local desktop - "ClickHouse"

I thought the problem might be related to the local machine, because some data sources can be connected extract

**Comment by Fliner042** [comment]
@dima-altinity 

Thanks, I'll look this way
