### ISSUE TITLE
SQLNumParams support

### ISSUE THREAD

**Issue by nvm1** [ClickHouse/clickhouse-odbc#53]
Hi,

Could you please look into the issue with turbodbc (python library) that I ran into. It seems that Clickhouse ODBC doesn't support one of the core ODBC features and I'm just currious if it's possible to fix it somehow.

https://github.com/blue-yonder/turbodbc/issues/144

**Comment by MathMagique** [comment]
It is basically about the Clickhouse ODBC driver not supporting parameters properly, and thus being non-compliant with the ODBC core level interface.

**Comment by MathMagique** [comment]
It is probably closely related to #27

**Comment by traceon** [comment]
Implemented in `master`.

**Comment by Enmk** [comment]
@nvm1 could you please check if issue is resolved now?

**Comment by nvm1** [comment]
@Enmk , i'd love to, but I'm afraid I don't uderstand how to setup the version from master on windows without msi :(

**Comment by traceon** [comment]
We are preparing the next release, it will be made available soon, msi's will be published too.

**Comment by nvm1** [comment]
@traceon, super, looking forward to the releas! I will test it asap and get back with the results ;)

**Comment by filimonov** [comment]
@nvm1 please try https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.0.20191028

**Comment by nvm1** [comment]
@filimonov , @traceon , @Enmk , thank you for the efforts, guys, but the issue is still there. The logs for `select 1` query:
[SQL.LOG](https://github.com/ClickHouse/clickhouse-odbc/files/3780212/SQL.LOG)

**Comment by traceon** [comment]
Oh, ok, I see where the problem is. The function is not exported.

**Comment by traceon** [comment]
Please give this a try: https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.1.1.20191108

**Comment by nvm1** [comment]
@traceon, it is alive! I managed to connect and obtain some data. Thank you! The only problem that I currently see, is that turbodbc is surprisingly 30-40% slower than pyodbc, while in other cases like postgresql or mysql it's like 50-200% faster. I guess the problem is somewhere in the communication between clickhouse-odbc and turbodbc. I'm not sure if you guys want and look into that, but if you will, probably @MathMagique could help to diagnoze the problem. From my side I'd happy to actively participate in tests :)

**Comment by traceon** [comment]
@nvm1 Glad it improved things for you!

Regarding performance, it would really help if you prove some self-contained reproducible cases, with both pyodbc and turbodbc, that could be used as reference for the problem and, hopefully, the improvement. Maybe in a separate issue?

**Comment by filimonov** [comment]
Closing this as SQLNumParams is now supported.

@nvm1 @MathMagique please open issue with samples showing performance difference. We definitely will look on that and will try to improve driver if possible.
