### ISSUE TITLE
Unknown identifier on Nullable(String) column

### ISSUE THREAD

**Issue by andreAmorimF** [ClickHouse/clickhouse-odbc#65]
Trying to connect from Tableau, using the _2018-02-01_ driver release, and getting the following error:

```
Received error: Code: 47, e.displayText() = DB::Exception: Unknown identifier: loved_songs.title, e.what() = DB::Exception
```

If it helps, the target table is using the _Log_ engine, with the following schema: 

```
CREATE TABLE test.loved_songs(
title Nullable(String),
song_id Float32,
artist_name Nullable(String),
datetime String) ENGINE  = Log;
```

I saw a similar error when using an older version of JDBC driver : https://github.com/dbeaver/dbeaver/issues/1959 and so I suspect this problem can persist on ODBC. I can try to provide more info, if necessary.

**Comment by proller** [comment]
What query fails?
Now it looks like you create table test.loved_songs but use default.loved_songs

**Comment by filimonov** [comment]
No updates for a longer time. Please recheck on latest versions of odbc driver and ClickHouse, and create a new issue if you will meet such behaviour again.
