### ISSUE TITLE
The ODBC error connect Power BI

### ISSUE THREAD

**Issue by DandelionWenjing** [ClickHouse/clickhouse-odbc#92]
Hi all,
I tried to use the Power BI to connect clickhouse odbc driver while met the following error:

Feedback Type:
Frown (Error)

Timestamp:
2018-07-12T06:23:06.6483545Z

Local Time:
2018-07-12T14:23:06.6483545+08:00

Session ID:
4004306b-ba15-4bc7-966c-9c202418c1f6

Release:
June 2018

Product Version:
2.59.5135.781 (PBIDesktop) (x64)

Error Message:
OLE DB or ODBC error: [DataSource.Error] ODBC: ERROR [HY000] HTTP status code: 500
Received error:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 12 (line 1, col 12): 1000001
    `TimeStamp`
from `default`.`TrafficTable4`
group by `TimeStamp`. Expected one of: identifier, alias, AS, token, AND, OR, UNION ALL, BETWEEN, IS, LIKE, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, Dot, Arrow, QuestionMark, ORDER BY, SETTINGS, INTO OUTFILE, FORMAT, FROM, PREWHERE, WHERE, WITH, HAVING, LIMIT, GROUP BY, e.what() = DB::Exception

OS Version:
Microsoft Windows NT 10.0.17134.0 (x64 zh-CN)

CLR Version:
4.7 or later [Release Number = 461808]

Peak Virtual Memory:
38.2 GB

Private Memory:
329 MB

Peak Working Set:
466 MB

IE Version:
11.112.17134.0

User ID:
db8cee20-5c05-4896-8470-a1fa38cf1cee

Workbook Package Info:
1* - zh-CN, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Model Default Mode:
DirectQuery

Snapshot Trace Logs:
C:\Users\wenzhao\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot977727484.zip

Performance Trace Logs:
C:\Users\wenzhao\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Enabled Preview Features:
CustomConnectors

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_EnableReportTheme
PBI_newFromWeb
PBI_SpanishLinguisticsEnabled
PBI_qnaExplore
PBI_variationUIChange
PBI_canvasTooltips
PBI_showIncrementalRefreshPolicy

Disabled DirectQuery Options:
PBI_DirectQuery_Unrestricted
TreatHanaAsRelationalSource

Cloud:
MSIT

DPI Scale:
100%

Supported Services:
Power BI

Formulas:

section Section1;

shared TrafficTable4 = let
    Source = DirectCH.Database("ClickhouseA"),
    TrafficTable4_Table = Source{[Name="TrafficTable4",Kind="Table"]}[Data]
in
    TrafficTable4_Table;

Wenjing Zhao

**Comment by DandelionWenjing** [comment]
Also the Visual studio version is the Enterprise version.

**Comment by proller** [comment]
can you show full failed query?
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 12 (line 1, col 12): 1000001
TimeStamp from default.TrafficTable4

maybe from clickhouse server logs ?

**Comment by filimonov** [comment]
No updates for a longer time. Please recheck newer version, and create a new issue if you will meet such behaviour again.
